// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/transformer (interfaces: FeaturesService)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=../../mocks/services/transformer/mock_features.go -package mock_features github.com/rudderlabs/rudder-server/services/transformer FeaturesService
//

// Package mock_features is a generated GoMock package.
package mock_features

import (
	gomock "go.uber.org/mock/gomock"
)

// MockFeaturesService is a mock of FeaturesService interface.
type MockFeaturesService struct {
	ctrl     *gomock.Controller
	recorder *MockFeaturesServiceMockRecorder
	isgomock struct{}
}

// MockFeaturesServiceMockRecorder is the mock recorder for MockFeaturesService.
type MockFeaturesServiceMockRecorder struct {
	mock *MockFeaturesService
}

// NewMockFeaturesService creates a new mock instance.
func NewMockFeaturesService(ctrl *gomock.Controller) *MockFeaturesService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeaturesService) EXPECT() *MockFeaturesServiceMockRecorder {
	_ = "STUB: not implemented"

	// Regulations mocks base method.
	return nil
}

func (m *MockFeaturesService) Regulations() []string { _ = "STUB: not implemented"; return nil }

// Regulations indicates an expected call of Regulations.
func (mr *MockFeaturesServiceMockRecorder) Regulations() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RouterTransform mocks base method.
func (m *MockFeaturesService) RouterTransform(destType string) bool {
	_ = "STUB: not implemented"
	return false
}

// RouterTransform indicates an expected call of RouterTransform.
func (mr *MockFeaturesServiceMockRecorder) RouterTransform(destType any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SourceTransformerVersion mocks base method.
func (m *MockFeaturesService) SourceTransformerVersion() string {
	_ = "STUB: not implemented"
	return ""
}

// SourceTransformerVersion indicates an expected call of SourceTransformerVersion.
func (mr *MockFeaturesServiceMockRecorder) SourceTransformerVersion() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SupportDestTransformCompactedPayloadV1 mocks base method.
func (m *MockFeaturesService) SupportDestTransformCompactedPayloadV1() bool {
	_ = "STUB: not implemented"
	return false
}

// SupportDestTransformCompactedPayloadV1 indicates an expected call of SupportDestTransformCompactedPayloadV1.
func (mr *MockFeaturesServiceMockRecorder) SupportDestTransformCompactedPayloadV1() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TransformerProxyVersion mocks base method.
func (m *MockFeaturesService) TransformerProxyVersion() string {
	_ = "STUB: not implemented"
	return ""
}

// TransformerProxyVersion indicates an expected call of TransformerProxyVersion.
func (mr *MockFeaturesServiceMockRecorder) TransformerProxyVersion() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Wait mocks base method.
func (m *MockFeaturesService) Wait() chan struct{} { _ = "STUB: not implemented"; return nil }

// Wait indicates an expected call of Wait.
func (mr *MockFeaturesServiceMockRecorder) Wait() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
