// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/jobsdb (interfaces: JobsDB)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/jobsdb/mock_jobsdb.go -package=mocks_jobsdb github.com/rudderlabs/rudder-server/jobsdb JobsDB
//

// Package mocks_jobsdb is a generated GoMock package.
package mocks_jobsdb

import (
	context "context"
	json "encoding/json"
	time "time"

	uuid "github.com/google/uuid"
	jobsdb "github.com/rudderlabs/rudder-server/jobsdb"
	rmetrics "github.com/rudderlabs/rudder-server/services/rmetrics"
	tx "github.com/rudderlabs/rudder-server/utils/tx"
	gomock "go.uber.org/mock/gomock"
)

// MockJobsDB is a mock of JobsDB interface.
type MockJobsDB struct {
	ctrl     *gomock.Controller
	recorder *MockJobsDBMockRecorder
	isgomock struct{}
}

// MockJobsDBMockRecorder is the mock recorder for MockJobsDB.
type MockJobsDBMockRecorder struct {
	mock *MockJobsDB
}

// NewMockJobsDB creates a new mock instance.
func NewMockJobsDB(ctrl *gomock.Controller) *MockJobsDB { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobsDB) EXPECT() *MockJobsDBMockRecorder {
	_ = "STUB: not implemented"

	// AddReadExcludedPartitionIDs mocks base method.
	return nil
}

func (m *MockJobsDB) AddReadExcludedPartitionIDs(ctx context.Context, partitionIDs []string) error {
	_ = "STUB: not implemented"
	return nil
}

// AddReadExcludedPartitionIDs indicates an expected call of AddReadExcludedPartitionIDs.
func (mr *MockJobsDBMockRecorder) AddReadExcludedPartitionIDs(ctx, partitionIDs any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteExecuting mocks base method.
func (m *MockJobsDB) DeleteExecuting() { _ = "STUB: not implemented"; return }

// DeleteExecuting indicates an expected call of DeleteExecuting.
func (mr *MockJobsDBMockRecorder) DeleteExecuting() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// FailExecuting mocks base method.
func (m *MockJobsDB) FailExecuting() { _ = "STUB: not implemented"; return }

// FailExecuting indicates an expected call of FailExecuting.
func (mr *MockJobsDBMockRecorder) FailExecuting() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetAborted mocks base method.
func (m *MockJobsDB) GetAborted(ctx context.Context, params jobsdb.GetQueryParams) (jobsdb.JobsResult, error) {
	_ = "STUB: not implemented"
	return *new(jobsdb.JobsResult), nil
}

// GetAborted indicates an expected call of GetAborted.
func (mr *MockJobsDBMockRecorder) GetAborted(ctx, params any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetDistinctParameterValues mocks base method.
func (m *MockJobsDB) GetDistinctParameterValues(ctx context.Context, parameter jobsdb.ParameterName, customValFilter string) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDistinctParameterValues indicates an expected call of GetDistinctParameterValues.
func (mr *MockJobsDBMockRecorder) GetDistinctParameterValues(ctx, parameter, customValFilter any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetFailed mocks base method.
func (m *MockJobsDB) GetFailed(ctx context.Context, params jobsdb.GetQueryParams) (jobsdb.JobsResult, error) {
	_ = "STUB: not implemented"
	return *new(jobsdb.JobsResult), nil
}

// GetFailed indicates an expected call of GetFailed.
func (mr *MockJobsDBMockRecorder) GetFailed(ctx, params any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetImporting mocks base method.
func (m *MockJobsDB) GetImporting(ctx context.Context, params jobsdb.GetQueryParams, more jobsdb.MoreToken) (*jobsdb.MoreJobsResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetImporting indicates an expected call of GetImporting.
func (mr *MockJobsDBMockRecorder) GetImporting(ctx, params, more any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetJobs mocks base method.
func (m *MockJobsDB) GetJobs(ctx context.Context, states []string, params jobsdb.GetQueryParams) (jobsdb.JobsResult, error) {
	_ = "STUB: not implemented"
	return *new(jobsdb.JobsResult), nil
}

// GetJobs indicates an expected call of GetJobs.
func (mr *MockJobsDBMockRecorder) GetJobs(ctx, states, params any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetJournalEntries mocks base method.
func (m *MockJobsDB) GetJournalEntries(opType string) []jobsdb.JournalEntryT {
	_ = "STUB: not implemented"
	return nil
}

// GetJournalEntries indicates an expected call of GetJournalEntries.
func (mr *MockJobsDBMockRecorder) GetJournalEntries(opType any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetPileUpCounts mocks base method.
func (m *MockJobsDB) GetPileUpCounts(ctx context.Context, cutoffTime time.Time, increaseFunc rmetrics.IncreasePendingEventsFunc) error {
	_ = "STUB: not implemented"
	return nil
}

// GetPileUpCounts indicates an expected call of GetPileUpCounts.
func (mr *MockJobsDBMockRecorder) GetPileUpCounts(ctx, cutoffTime, increaseFunc any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSucceeded mocks base method.
func (m *MockJobsDB) GetSucceeded(ctx context.Context, params jobsdb.GetQueryParams) (jobsdb.JobsResult, error) {
	_ = "STUB: not implemented"
	return *new(jobsdb.JobsResult), nil
}

// GetSucceeded indicates an expected call of GetSucceeded.
func (mr *MockJobsDBMockRecorder) GetSucceeded(ctx, params any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetToProcess mocks base method.
func (m *MockJobsDB) GetToProcess(ctx context.Context, params jobsdb.GetQueryParams, more jobsdb.MoreToken) (*jobsdb.MoreJobsResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetToProcess indicates an expected call of GetToProcess.
func (mr *MockJobsDBMockRecorder) GetToProcess(ctx, params, more any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUnprocessed mocks base method.
func (m *MockJobsDB) GetUnprocessed(ctx context.Context, params jobsdb.GetQueryParams) (jobsdb.JobsResult, error) {
	_ = "STUB: not implemented"
	return *new(jobsdb.JobsResult), nil
}

// GetUnprocessed indicates an expected call of GetUnprocessed.
func (mr *MockJobsDBMockRecorder) GetUnprocessed(ctx, params any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetWaiting mocks base method.
func (m *MockJobsDB) GetWaiting(ctx context.Context, params jobsdb.GetQueryParams) (jobsdb.JobsResult, error) {
	_ = "STUB: not implemented"
	return *new(jobsdb.JobsResult), nil
}

// GetWaiting indicates an expected call of GetWaiting.
func (mr *MockJobsDBMockRecorder) GetWaiting(ctx, params any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Identifier mocks base method.
func (m *MockJobsDB) Identifier() string { _ = "STUB: not implemented"; return "" }

// Identifier indicates an expected call of Identifier.
func (mr *MockJobsDBMockRecorder) Identifier() *gomock.Call { _ = "STUB: not implemented"; return nil }

// IsMasterBackupEnabled mocks base method.
func (m *MockJobsDB) IsMasterBackupEnabled() bool { _ = "STUB: not implemented"; return false }

// IsMasterBackupEnabled indicates an expected call of IsMasterBackupEnabled.
func (mr *MockJobsDBMockRecorder) IsMasterBackupEnabled() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// JournalDeleteEntry mocks base method.
func (m *MockJobsDB) JournalDeleteEntry(opID int64) { _ = "STUB: not implemented"; return }

// JournalDeleteEntry indicates an expected call of JournalDeleteEntry.
func (mr *MockJobsDBMockRecorder) JournalDeleteEntry(opID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// JournalMarkDone mocks base method.
func (m *MockJobsDB) JournalMarkDone(opID int64) error { _ = "STUB: not implemented"; return nil }

// JournalMarkDone indicates an expected call of JournalMarkDone.
func (mr *MockJobsDBMockRecorder) JournalMarkDone(opID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// JournalMarkStart mocks base method.
func (m *MockJobsDB) JournalMarkStart(opType string, opPayload json.RawMessage) (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// JournalMarkStart indicates an expected call of JournalMarkStart.
func (mr *MockJobsDBMockRecorder) JournalMarkStart(opType, opPayload any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Ping mocks base method.
func (m *MockJobsDB) Ping() error { _ = "STUB: not implemented"; return nil }

// Ping indicates an expected call of Ping.
func (mr *MockJobsDBMockRecorder) Ping() *gomock.Call { _ = "STUB: not implemented"; return nil }

// RefreshDSList mocks base method.
func (m *MockJobsDB) RefreshDSList(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// RefreshDSList indicates an expected call of RefreshDSList.
func (mr *MockJobsDBMockRecorder) RefreshDSList(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoveReadExcludedPartitionIDs mocks base method.
func (m *MockJobsDB) RemoveReadExcludedPartitionIDs(ctx context.Context, partitionIDs []string) error {
	_ = "STUB: not implemented"
	return nil
}

// RemoveReadExcludedPartitionIDs indicates an expected call of RemoveReadExcludedPartitionIDs.
func (mr *MockJobsDBMockRecorder) RemoveReadExcludedPartitionIDs(ctx, partitionIDs any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Start mocks base method.
func (m *MockJobsDB) Start() error { _ = "STUB: not implemented"; return nil }

// Start indicates an expected call of Start.
func (mr *MockJobsDBMockRecorder) Start() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Stop mocks base method.
func (m *MockJobsDB) Stop() { _ = "STUB: not implemented"; return }

// Stop indicates an expected call of Stop.
func (mr *MockJobsDBMockRecorder) Stop() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Store mocks base method.
func (m *MockJobsDB) Store(ctx context.Context, jobList []*jobsdb.JobT) error {
	_ = "STUB: not implemented"
	return nil
}

// Store indicates an expected call of Store.
func (mr *MockJobsDBMockRecorder) Store(ctx, jobList any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StoreEachBatchRetry mocks base method.
func (m *MockJobsDB) StoreEachBatchRetry(ctx context.Context, jobBatches [][]*jobsdb.JobT) map[uuid.UUID]string {
	_ = "STUB: not implemented"
	return nil
}

// StoreEachBatchRetry indicates an expected call of StoreEachBatchRetry.
func (mr *MockJobsDBMockRecorder) StoreEachBatchRetry(ctx, jobBatches any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StoreEachBatchRetryInTx mocks base method.
func (m *MockJobsDB) StoreEachBatchRetryInTx(ctx context.Context, arg1 jobsdb.StoreSafeTx, jobBatches [][]*jobsdb.JobT) (map[uuid.UUID]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// StoreEachBatchRetryInTx indicates an expected call of StoreEachBatchRetryInTx.
func (mr *MockJobsDBMockRecorder) StoreEachBatchRetryInTx(ctx, arg1, jobBatches any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StoreInTx mocks base method.
func (m *MockJobsDB) StoreInTx(ctx context.Context, arg1 jobsdb.StoreSafeTx, jobList []*jobsdb.JobT) error {
	_ = "STUB: not implemented"
	return nil
}

// StoreInTx indicates an expected call of StoreInTx.
func (mr *MockJobsDBMockRecorder) StoreInTx(ctx, arg1, jobList any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateJobStatus mocks base method.
func (m *MockJobsDB) UpdateJobStatus(ctx context.Context, statusList []*jobsdb.JobStatusT) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateJobStatus indicates an expected call of UpdateJobStatus.
func (mr *MockJobsDBMockRecorder) UpdateJobStatus(ctx, statusList any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateJobStatusInTx mocks base method.
func (m *MockJobsDB) UpdateJobStatusInTx(ctx context.Context, arg1 jobsdb.UpdateSafeTx, statusList []*jobsdb.JobStatusT) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateJobStatusInTx indicates an expected call of UpdateJobStatusInTx.
func (mr *MockJobsDBMockRecorder) UpdateJobStatusInTx(ctx, arg1, statusList any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithStoreSafeTx mocks base method.
func (m *MockJobsDB) WithStoreSafeTx(arg0 context.Context, arg1 func(jobsdb.StoreSafeTx) error) error {
	_ = "STUB: not implemented"
	return nil
}

// WithStoreSafeTx indicates an expected call of WithStoreSafeTx.
func (mr *MockJobsDBMockRecorder) WithStoreSafeTx(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithStoreSafeTxFromTx mocks base method.
func (m *MockJobsDB) WithStoreSafeTxFromTx(arg0 context.Context, arg1 *tx.Tx, arg2 func(jobsdb.StoreSafeTx) error) error {
	_ = "STUB: not implemented"
	return nil
}

// WithStoreSafeTxFromTx indicates an expected call of WithStoreSafeTxFromTx.
func (mr *MockJobsDBMockRecorder) WithStoreSafeTxFromTx(arg0, arg1, arg2 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithTx mocks base method.
func (m *MockJobsDB) WithTx(arg0 context.Context, arg1 func(*tx.Tx) error) error {
	_ = "STUB: not implemented"
	return nil
}

// WithTx indicates an expected call of WithTx.
func (mr *MockJobsDBMockRecorder) WithTx(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithUpdateSafeTx mocks base method.
func (m *MockJobsDB) WithUpdateSafeTx(arg0 context.Context, arg1 func(jobsdb.UpdateSafeTx) error) error {
	_ = "STUB: not implemented"
	return nil
}

// WithUpdateSafeTx indicates an expected call of WithUpdateSafeTx.
func (mr *MockJobsDBMockRecorder) WithUpdateSafeTx(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithUpdateSafeTxFromTx mocks base method.
func (m *MockJobsDB) WithUpdateSafeTxFromTx(ctx context.Context, arg1 *tx.Tx, f func(jobsdb.UpdateSafeTx) error) error {
	_ = "STUB: not implemented"
	return nil
}

// WithUpdateSafeTxFromTx indicates an expected call of WithUpdateSafeTxFromTx.
func (mr *MockJobsDBMockRecorder) WithUpdateSafeTxFromTx(ctx, arg1, f any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
