// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/backend-config/dynamicconfig (interfaces: Cache)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/backend-config/dynamicconfig/mock_dynamic_config.go -package=mock_dynamicconfig github.com/rudderlabs/rudder-server/backend-config/dynamicconfig Cache
//

// Package mock_dynamicconfig is a generated GoMock package.
package mock_dynamicconfig

import (
	dynamicconfig "github.com/rudderlabs/rudder-server/backend-config/dynamicconfig"
	gomock "go.uber.org/mock/gomock"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	_ = "STUB: not implemented"

	// Get mocks base method.
	return nil
}

func (m *MockCache) Get(destID string) (*dynamicconfig.DestinationRevisionInfo, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

// Get indicates an expected call of Get.
func (mr *MockCacheMockRecorder) Get(destID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Len mocks base method.
func (m *MockCache) Len() int { _ = "STUB: not implemented"; return 0 }

// Len indicates an expected call of Len.
func (mr *MockCacheMockRecorder) Len() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Set mocks base method.
func (m *MockCache) Set(destID string, info *dynamicconfig.DestinationRevisionInfo) {
	_ = "STUB: not implemented"
	return
}

// Set indicates an expected call of Set.
func (mr *MockCacheMockRecorder) Set(destID, info any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
