// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/klaviyobulkupload (interfaces: KlaviyoAPIService)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/router/klaviyobulkupload/klaviyobulkupload_mock.go -package=mocks github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/klaviyobulkupload KlaviyoAPIService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	klaviyobulkupload "github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/klaviyobulkupload"
	gomock "go.uber.org/mock/gomock"
)

// MockKlaviyoAPIService is a mock of KlaviyoAPIService interface.
type MockKlaviyoAPIService struct {
	ctrl     *gomock.Controller
	recorder *MockKlaviyoAPIServiceMockRecorder
	isgomock struct{}
}

// MockKlaviyoAPIServiceMockRecorder is the mock recorder for MockKlaviyoAPIService.
type MockKlaviyoAPIServiceMockRecorder struct {
	mock *MockKlaviyoAPIService
}

// NewMockKlaviyoAPIService creates a new mock instance.
func NewMockKlaviyoAPIService(ctrl *gomock.Controller) *MockKlaviyoAPIService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKlaviyoAPIService) EXPECT() *MockKlaviyoAPIServiceMockRecorder {
	_ = "STUB: not implemented"

	// GetUploadErrors mocks base method.
	return nil
}

func (m *MockKlaviyoAPIService) GetUploadErrors(importId string) (*klaviyobulkupload.UploadStatusResp, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUploadErrors indicates an expected call of GetUploadErrors.
func (mr *MockKlaviyoAPIServiceMockRecorder) GetUploadErrors(importId any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUploadStatus mocks base method.
func (m *MockKlaviyoAPIService) GetUploadStatus(importId string) (*klaviyobulkupload.PollResp, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUploadStatus indicates an expected call of GetUploadStatus.
func (mr *MockKlaviyoAPIServiceMockRecorder) GetUploadStatus(importId any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UploadProfiles mocks base method.
func (m *MockKlaviyoAPIService) UploadProfiles(profiles klaviyobulkupload.Payload) (*klaviyobulkupload.UploadResp, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UploadProfiles indicates an expected call of UploadProfiles.
func (mr *MockKlaviyoAPIServiceMockRecorder) UploadProfiles(profiles any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
