// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_service.go -package=service github.com/rudderlabs/rudder-server/regulation-worker/internal/service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"

	backendconfig "github.com/rudderlabs/rudder-server/backend-config"
	model "github.com/rudderlabs/rudder-server/regulation-worker/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAPIClient is a mock of APIClient interface.
type MockAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockAPIClientMockRecorder
	isgomock struct{}
}

// MockAPIClientMockRecorder is the mock recorder for MockAPIClient.
type MockAPIClientMockRecorder struct {
	mock *MockAPIClient
}

// NewMockAPIClient creates a new mock instance.
func NewMockAPIClient(ctrl *gomock.Controller) *MockAPIClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIClient) EXPECT() *MockAPIClientMockRecorder {
	_ = "STUB: not implemented"

	// Get mocks base method.
	return nil
}

func (m *MockAPIClient) Get(ctx context.Context) (model.Job, error) {
	_ = "STUB: not implemented"
	return *new(model.Job), nil
}

// Get indicates an expected call of Get.
func (mr *MockAPIClientMockRecorder) Get(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateStatus mocks base method.
func (m *MockAPIClient) UpdateStatus(ctx context.Context, status model.JobStatus, jobID int) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockAPIClientMockRecorder) UpdateStatus(ctx, status, jobID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Mockdest is a mock of dest interface.
type Mockdest struct {
	ctrl     *gomock.Controller
	recorder *MockdestMockRecorder
	isgomock struct{}
}

// MockdestMockRecorder is the mock recorder for Mockdest.
type MockdestMockRecorder struct {
	mock *Mockdest
}

// NewMockdest creates a new mock instance.
func NewMockdest(ctrl *gomock.Controller) *Mockdest { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdest) EXPECT() *MockdestMockRecorder {
	_ = "STUB: not implemented"

	// GetDestination mocks base method.
	return nil
}

func (m *Mockdest) GetDestination(destID string) (*backendconfig.DestinationT, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDestination indicates an expected call of GetDestination.
func (mr *MockdestMockRecorder) GetDestination(destID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Mockdeleter is a mock of deleter interface.
type Mockdeleter struct {
	ctrl     *gomock.Controller
	recorder *MockdeleterMockRecorder
	isgomock struct{}
}

// MockdeleterMockRecorder is the mock recorder for Mockdeleter.
type MockdeleterMockRecorder struct {
	mock *Mockdeleter
}

// NewMockdeleter creates a new mock instance.
func NewMockdeleter(ctrl *gomock.Controller) *Mockdeleter { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdeleter) EXPECT() *MockdeleterMockRecorder {
	_ = "STUB: not implemented"

	// Delete mocks base method.
	return nil
}

func (m *Mockdeleter) Delete(ctx context.Context, job model.Job, dest *backendconfig.DestinationT) model.JobStatus {
	_ = "STUB: not implemented"
	return *new(model.JobStatus)
}

// Delete indicates an expected call of Delete.
func (mr *MockdeleterMockRecorder) Delete(ctx, job, dest any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
