// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/streammanager/bqstream (interfaces: BQClient)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/services/streammanager/bqstream/mock_bqstream.go -package mock_bqstream github.com/rudderlabs/rudder-server/services/streammanager/bqstream BQClient
//

// Package mock_bqstream is a generated GoMock package.
package mock_bqstream

import (
	context "context"

	bqstream "github.com/rudderlabs/rudder-server/services/streammanager/bqstream"
	gomock "go.uber.org/mock/gomock"
)

// MockBQClient is a mock of BQClient interface.
type MockBQClient struct {
	ctrl     *gomock.Controller
	recorder *MockBQClientMockRecorder
	isgomock struct{}
}

// MockBQClientMockRecorder is the mock recorder for MockBQClient.
type MockBQClientMockRecorder struct {
	mock *MockBQClient
}

// NewMockBQClient creates a new mock instance.
func NewMockBQClient(ctrl *gomock.Controller) *MockBQClient { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBQClient) EXPECT() *MockBQClientMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockBQClient) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockBQClientMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Put mocks base method.
func (m *MockBQClient) Put(ctx context.Context, datasetID, tableID string, records []*bqstream.GenericRecord) error {
	_ = "STUB: not implemented"
	return nil
}

// Put indicates an expected call of Put.
func (mr *MockBQClientMockRecorder) Put(ctx, datasetID, tableID, records any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
