// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/marketo-bulk-upload (interfaces: MarketoAPIServiceInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	marketobulkupload "github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/marketo-bulk-upload"
)

// MockMarketoAPIServiceInterface is a mock of MarketoAPIServiceInterface interface.
type MockMarketoAPIServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMarketoAPIServiceInterfaceMockRecorder
}

// MockMarketoAPIServiceInterfaceMockRecorder is the mock recorder for MockMarketoAPIServiceInterface.
type MockMarketoAPIServiceInterfaceMockRecorder struct {
	mock *MockMarketoAPIServiceInterface
}

// NewMockMarketoAPIServiceInterface creates a new mock instance.
func NewMockMarketoAPIServiceInterface(ctrl *gomock.Controller) *MockMarketoAPIServiceInterface {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarketoAPIServiceInterface) EXPECT() *MockMarketoAPIServiceInterfaceMockRecorder {
	_ = "STUB: not implemented"

	// GetLeadStatus mocks base method.
	return nil
}

func (m *MockMarketoAPIServiceInterface) GetLeadStatus(arg0 string) ([]map[string]string, *marketobulkupload.APIError) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetLeadStatus indicates an expected call of GetLeadStatus.
func (mr *MockMarketoAPIServiceInterfaceMockRecorder) GetLeadStatus(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ImportLeads mocks base method.
func (m *MockMarketoAPIServiceInterface) ImportLeads(arg0, arg1 string) (string, *marketobulkupload.APIError) {
	_ = "STUB: not implemented"
	return "", nil
}

// ImportLeads indicates an expected call of ImportLeads.
func (mr *MockMarketoAPIServiceInterfaceMockRecorder) ImportLeads(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PollImportStatus mocks base method.
func (m *MockMarketoAPIServiceInterface) PollImportStatus(arg0 string) (*marketobulkupload.MarketoResponse, *marketobulkupload.APIError) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PollImportStatus indicates an expected call of PollImportStatus.
func (mr *MockMarketoAPIServiceInterfaceMockRecorder) PollImportStatus(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
