// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/streammanager/firehose (interfaces: FirehoseClient)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/services/streammanager/firehose/mock_firehose.go -package mock_firehose github.com/rudderlabs/rudder-server/services/streammanager/firehose FirehoseClient
//

// Package mock_firehose is a generated GoMock package.
package mock_firehose

import (
	context "context"

	firehose "github.com/aws/aws-sdk-go-v2/service/firehose"
	gomock "go.uber.org/mock/gomock"
)

// MockFirehoseClient is a mock of FirehoseClient interface.
type MockFirehoseClient struct {
	ctrl     *gomock.Controller
	recorder *MockFirehoseClientMockRecorder
	isgomock struct{}
}

// MockFirehoseClientMockRecorder is the mock recorder for MockFirehoseClient.
type MockFirehoseClientMockRecorder struct {
	mock *MockFirehoseClient
}

// NewMockFirehoseClient creates a new mock instance.
func NewMockFirehoseClient(ctrl *gomock.Controller) *MockFirehoseClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFirehoseClient) EXPECT() *MockFirehoseClientMockRecorder {
	_ = "STUB: not implemented"

	// PutRecord mocks base method.
	return nil
}

func (m *MockFirehoseClient) PutRecord(ctx context.Context, input *firehose.PutRecordInput, opts ...func(*firehose.Options)) (*firehose.PutRecordOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutRecord indicates an expected call of PutRecord.
func (mr *MockFirehoseClientMockRecorder) PutRecord(ctx, input any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
