// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/streammanager/lambda (interfaces: LambdaClient)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=../../../mocks/services/streammanager/lambda/mock_lambda.go -package mock_lambda github.com/rudderlabs/rudder-server/services/streammanager/lambda LambdaClient
//

// Package mock_lambda is a generated GoMock package.
package mock_lambda

import (
	context "context"

	lambda "github.com/aws/aws-sdk-go-v2/service/lambda"
	gomock "go.uber.org/mock/gomock"
)

// MockLambdaClient is a mock of LambdaClient interface.
type MockLambdaClient struct {
	ctrl     *gomock.Controller
	recorder *MockLambdaClientMockRecorder
	isgomock struct{}
}

// MockLambdaClientMockRecorder is the mock recorder for MockLambdaClient.
type MockLambdaClientMockRecorder struct {
	mock *MockLambdaClient
}

// NewMockLambdaClient creates a new mock instance.
func NewMockLambdaClient(ctrl *gomock.Controller) *MockLambdaClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLambdaClient) EXPECT() *MockLambdaClientMockRecorder {
	_ = "STUB: not implemented"

	// Invoke mocks base method.
	return nil
}

func (m *MockLambdaClient) Invoke(ctx context.Context, input *lambda.InvokeInput, opts ...func(*lambda.Options)) (*lambda.InvokeOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Invoke indicates an expected call of Invoke.
func (mr *MockLambdaClientMockRecorder) Invoke(ctx, input any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
