// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/processor/transformer (interfaces: TransformerClients)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/processor/transformer/mock_transformer_clients.go -package=mocks_transformer_clients github.com/rudderlabs/rudder-server/processor/transformer TransformerClients
//

// Package mocks_transformer_clients is a generated GoMock package.
package mocks_transformer_clients

import (
	transformer "github.com/rudderlabs/rudder-server/processor/transformer"
	gomock "go.uber.org/mock/gomock"
)

// MockTransformerClients is a mock of TransformerClients interface.
type MockTransformerClients struct {
	ctrl     *gomock.Controller
	recorder *MockTransformerClientsMockRecorder
	isgomock struct{}
}

// MockTransformerClientsMockRecorder is the mock recorder for MockTransformerClients.
type MockTransformerClientsMockRecorder struct {
	mock *MockTransformerClients
}

// NewMockTransformerClients creates a new mock instance.
func NewMockTransformerClients(ctrl *gomock.Controller) *MockTransformerClients {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransformerClients) EXPECT() *MockTransformerClientsMockRecorder {
	_ = "STUB: not implemented"

	// Destination mocks base method.
	return nil
}

func (m *MockTransformerClients) Destination() transformer.DestinationClient {
	_ = "STUB: not implemented"
	return *new(transformer.DestinationClient)
}

// Destination indicates an expected call of Destination.
func (mr *MockTransformerClientsMockRecorder) Destination() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SrcHydration mocks base method.
func (m *MockTransformerClients) SrcHydration() transformer.SrcHydrationClient {
	_ = "STUB: not implemented"
	return *new(transformer.SrcHydrationClient)
}

// SrcHydration indicates an expected call of SrcHydration.
func (mr *MockTransformerClientsMockRecorder) SrcHydration() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TrackingPlan mocks base method.
func (m *MockTransformerClients) TrackingPlan() transformer.TrackingPlanClient {
	_ = "STUB: not implemented"
	return *new(transformer.TrackingPlanClient)
}

// TrackingPlan indicates an expected call of TrackingPlan.
func (mr *MockTransformerClientsMockRecorder) TrackingPlan() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// User mocks base method.
func (m *MockTransformerClients) User() transformer.UserClient {
	_ = "STUB: not implemented"
	return *new(transformer.UserClient)
}

// User indicates an expected call of User.
func (mr *MockTransformerClientsMockRecorder) User() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UserMirror mocks base method.
func (m *MockTransformerClients) UserMirror() transformer.UserClient {
	_ = "STUB: not implemented"
	return *new(transformer.UserClient)
}

// UserMirror indicates an expected call of UserMirror.
func (mr *MockTransformerClientsMockRecorder) UserMirror() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
