// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/oauth/v2 (interfaces: AuthIdentityProvider)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/services/oauthV2/mock_oauthV2.go -package=mock_oauthV2 github.com/rudderlabs/rudder-server/services/oauth/v2 AuthIdentityProvider
//

// Package mock_oauthV2 is a generated GoMock package.
package mock_oauthV2

import (
	identity "github.com/rudderlabs/rudder-server/services/controlplane/identity"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthIdentityProvider is a mock of AuthIdentityProvider interface.
type MockAuthIdentityProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAuthIdentityProviderMockRecorder
	isgomock struct{}
}

// MockAuthIdentityProviderMockRecorder is the mock recorder for MockAuthIdentityProvider.
type MockAuthIdentityProviderMockRecorder struct {
	mock *MockAuthIdentityProvider
}

// NewMockAuthIdentityProvider creates a new mock instance.
func NewMockAuthIdentityProvider(ctrl *gomock.Controller) *MockAuthIdentityProvider {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthIdentityProvider) EXPECT() *MockAuthIdentityProviderMockRecorder {
	_ = "STUB: not implemented"

	// Identity mocks base method.
	return nil
}

func (m *MockAuthIdentityProvider) Identity() identity.Identifier {
	_ = "STUB: not implemented"
	return *new(identity.Identifier)
}

// Identity indicates an expected call of Identity.
func (mr *MockAuthIdentityProviderMockRecorder) Identity() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
