// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/oauth/v2 (interfaces: OAuthHandler)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/services/oauthV2/mock_oauthhandler.go -package=mock_oauthV2 github.com/rudderlabs/rudder-server/services/oauth/v2 OAuthHandler
//

// Package mock_oauthV2 is a generated GoMock package.
package mock_oauthV2

import (
	json "encoding/json"

	v2 "github.com/rudderlabs/rudder-server/services/oauth/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuthHandler is a mock of OAuthHandler interface.
type MockOAuthHandler struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthHandlerMockRecorder
	isgomock struct{}
}

// MockOAuthHandlerMockRecorder is the mock recorder for MockOAuthHandler.
type MockOAuthHandlerMockRecorder struct {
	mock *MockOAuthHandler
}

// NewMockOAuthHandler creates a new mock instance.
func NewMockOAuthHandler(ctrl *gomock.Controller) *MockOAuthHandler {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthHandler) EXPECT() *MockOAuthHandlerMockRecorder {
	_ = "STUB: not implemented"

	// FetchToken mocks base method.
	return nil
}

func (m *MockOAuthHandler) FetchToken(params *v2.OAuthTokenParams) (json.RawMessage, v2.StatusCodeError) {
	_ = "STUB: not implemented"
	return *new(json.RawMessage), *new(v2.StatusCodeError)
}

// FetchToken indicates an expected call of FetchToken.
func (mr *MockOAuthHandlerMockRecorder) FetchToken(params any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RefreshToken mocks base method.
func (m *MockOAuthHandler) RefreshToken(params *v2.OAuthTokenParams, previousSecret json.RawMessage) (json.RawMessage, v2.StatusCodeError) {
	_ = "STUB: not implemented"
	return *new(json.RawMessage), *new(v2.StatusCodeError)
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockOAuthHandlerMockRecorder) RefreshToken(params, previousSecret any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
