// Code generated by MockGen. DO NOT EDIT.
// Source: net/http (interfaces: RoundTripper)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/services/oauthV2/mock_roundtripper.go -package=mock_oauthV2 net/http RoundTripper
//

// Package mock_oauthV2 is a generated GoMock package.
package mock_oauthV2

import (
	http "net/http"

	gomock "go.uber.org/mock/gomock"
)

// MockRoundTripper is a mock of RoundTripper interface.
type MockRoundTripper struct {
	ctrl     *gomock.Controller
	recorder *MockRoundTripperMockRecorder
	isgomock struct{}
}

// MockRoundTripperMockRecorder is the mock recorder for MockRoundTripper.
type MockRoundTripperMockRecorder struct {
	mock *MockRoundTripper
}

// NewMockRoundTripper creates a new mock instance.
func NewMockRoundTripper(ctrl *gomock.Controller) *MockRoundTripper {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoundTripper) EXPECT() *MockRoundTripperMockRecorder {
	_ = "STUB: not implemented"

	// RoundTrip mocks base method.
	return nil
}

func (m *MockRoundTripper) RoundTrip(arg0 *http.Request) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RoundTrip indicates an expected call of RoundTrip.
func (mr *MockRoundTripperMockRecorder) RoundTrip(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
