// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/oauth/v2/controlplane (interfaces: Connector)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/services/oauthV2/mock_cp_connector.go -package=mock_oauthV2 github.com/rudderlabs/rudder-server/services/oauth/v2/controlplane Connector
//

// Package mock_oauthV2 is a generated GoMock package.
package mock_oauthV2

import (
	controlplane "github.com/rudderlabs/rudder-server/services/oauth/v2/controlplane"
	gomock "go.uber.org/mock/gomock"
)

// MockConnector is a mock of Connector interface.
type MockConnector struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorMockRecorder
	isgomock struct{}
}

// MockConnectorMockRecorder is the mock recorder for MockConnector.
type MockConnectorMockRecorder struct {
	mock *MockConnector
}

// NewMockConnector creates a new mock instance.
func NewMockConnector(ctrl *gomock.Controller) *MockConnector {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnector) EXPECT() *MockConnectorMockRecorder {
	_ = "STUB: not implemented"

	// CpApiCall mocks base method.
	return nil
}

func (m *MockConnector) CpApiCall(cpReq *controlplane.Request) (int, string) {
	_ = "STUB: not implemented"
	return 0, ""
}

// CpApiCall indicates an expected call of CpApiCall.
func (mr *MockConnectorMockRecorder) CpApiCall(cpReq any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
