// Code generated by MockGen. DO NOT EDIT.
// Source: rsources.go
//
// Generated by this command:
//
//	mockgen -source=rsources.go -destination=mock_rsources.go -package=rsources github.com/rudderlabs/rudder-server/services/rsources JobService
//

// Package rsources is a generated GoMock package.
package rsources

import (
	context "context"
	sql "database/sql"

	gomock "go.uber.org/mock/gomock"
)

// MockStatsIncrementer is a mock of StatsIncrementer interface.
type MockStatsIncrementer struct {
	ctrl     *gomock.Controller
	recorder *MockStatsIncrementerMockRecorder
	isgomock struct{}
}

// MockStatsIncrementerMockRecorder is the mock recorder for MockStatsIncrementer.
type MockStatsIncrementerMockRecorder struct {
	mock *MockStatsIncrementer
}

// NewMockStatsIncrementer creates a new mock instance.
func NewMockStatsIncrementer(ctrl *gomock.Controller) *MockStatsIncrementer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsIncrementer) EXPECT() *MockStatsIncrementerMockRecorder {
	_ = "STUB: not implemented"

	// IncrementStats mocks base method.
	return nil
}

func (m *MockStatsIncrementer) IncrementStats(ctx context.Context, tx *sql.Tx, jobRunId string, key JobTargetKey, stats Stats) error {
	_ = "STUB: not implemented"
	return nil
}

// IncrementStats indicates an expected call of IncrementStats.
func (mr *MockStatsIncrementerMockRecorder) IncrementStats(ctx, tx, jobRunId, key, stats any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockJobService is a mock of JobService interface.
type MockJobService struct {
	ctrl     *gomock.Controller
	recorder *MockJobServiceMockRecorder
	isgomock struct{}
}

// MockJobServiceMockRecorder is the mock recorder for MockJobService.
type MockJobServiceMockRecorder struct {
	mock *MockJobService
}

// NewMockJobService creates a new mock instance.
func NewMockJobService(ctrl *gomock.Controller) *MockJobService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobService) EXPECT() *MockJobServiceMockRecorder {
	_ = "STUB: not implemented"

	// AddFailedRecords mocks base method.
	return nil
}

func (m *MockJobService) AddFailedRecords(ctx context.Context, tx *sql.Tx, jobRunId string, key JobTargetKey, records []FailedRecord) error {
	_ = "STUB: not implemented"
	return nil
}

// AddFailedRecords indicates an expected call of AddFailedRecords.
func (mr *MockJobServiceMockRecorder) AddFailedRecords(ctx, tx, jobRunId, key, records any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CleanupLoop mocks base method.
func (m *MockJobService) CleanupLoop(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// CleanupLoop indicates an expected call of CleanupLoop.
func (mr *MockJobServiceMockRecorder) CleanupLoop(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Delete mocks base method.
func (m *MockJobService) Delete(ctx context.Context, jobRunId string, filter JobFilter) error {
	_ = "STUB: not implemented"
	return nil
}

// Delete indicates an expected call of Delete.
func (mr *MockJobServiceMockRecorder) Delete(ctx, jobRunId, filter any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteFailedRecords mocks base method.
func (m *MockJobService) DeleteFailedRecords(ctx context.Context, jobRunId string, filter JobFilter) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteFailedRecords indicates an expected call of DeleteFailedRecords.
func (mr *MockJobServiceMockRecorder) DeleteFailedRecords(ctx, jobRunId, filter any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteJobStatus mocks base method.
func (m *MockJobService) DeleteJobStatus(ctx context.Context, jobRunId string, filter JobFilter) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteJobStatus indicates an expected call of DeleteJobStatus.
func (mr *MockJobServiceMockRecorder) DeleteJobStatus(ctx, jobRunId, filter any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetFailedRecords mocks base method.
func (m *MockJobService) GetFailedRecords(ctx context.Context, jobRunId string, filter JobFilter, paging PagingInfo) (JobFailedRecordsV2, error) {
	_ = "STUB: not implemented"
	return *new(JobFailedRecordsV2), nil
}

// GetFailedRecords indicates an expected call of GetFailedRecords.
func (mr *MockJobServiceMockRecorder) GetFailedRecords(ctx, jobRunId, filter, paging any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetFailedRecordsV1 mocks base method.
func (m *MockJobService) GetFailedRecordsV1(ctx context.Context, jobRunId string, filter JobFilter, paging PagingInfo) (JobFailedRecordsV1, error) {
	_ = "STUB: not implemented"
	return *new(JobFailedRecordsV1), nil
}

// GetFailedRecordsV1 indicates an expected call of GetFailedRecordsV1.
func (mr *MockJobServiceMockRecorder) GetFailedRecordsV1(ctx, jobRunId, filter, paging any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetStatus mocks base method.
func (m *MockJobService) GetStatus(ctx context.Context, jobRunId string, filter JobFilter) (JobStatus, error) {
	_ = "STUB: not implemented"
	return *new(JobStatus), nil
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockJobServiceMockRecorder) GetStatus(ctx, jobRunId, filter any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IncrementStats mocks base method.
func (m *MockJobService) IncrementStats(ctx context.Context, tx *sql.Tx, jobRunId string, key JobTargetKey, stats Stats) error {
	_ = "STUB: not implemented"
	return nil
}

// IncrementStats indicates an expected call of IncrementStats.
func (mr *MockJobServiceMockRecorder) IncrementStats(ctx, tx, jobRunId, key, stats any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Monitor mocks base method.
func (m *MockJobService) Monitor(ctx context.Context, lagGauge, replicationSlotGauge Gauger) {
	_ = "STUB: not implemented"
	return
}

// Monitor indicates an expected call of Monitor.
func (mr *MockJobServiceMockRecorder) Monitor(ctx, lagGauge, replicationSlotGauge any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockGauger is a mock of Gauger interface.
type MockGauger struct {
	ctrl     *gomock.Controller
	recorder *MockGaugerMockRecorder
	isgomock struct{}
}

// MockGaugerMockRecorder is the mock recorder for MockGauger.
type MockGaugerMockRecorder struct {
	mock *MockGauger
}

// NewMockGauger creates a new mock instance.
func NewMockGauger(ctrl *gomock.Controller) *MockGauger { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGauger) EXPECT() *MockGaugerMockRecorder {
	_ = "STUB: not implemented"

	// Gauge mocks base method.
	return nil
}

func (m *MockGauger) Gauge(arg0 any) { _ = "STUB: not implemented"; return }

// Gauge indicates an expected call of Gauge.
func (mr *MockGaugerMockRecorder) Gauge(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
