// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/schema-forwarder (interfaces: Forwarder)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/jobs-forwarder/mock_jobs_forwarder.go -package=mock_jobs_forwarder github.com/rudderlabs/rudder-server/schema-forwarder Forwarder
//

// Package mock_jobs_forwarder is a generated GoMock package.
package mock_jobs_forwarder

import (
	gomock "go.uber.org/mock/gomock"
)

// MockForwarder is a mock of Forwarder interface.
type MockForwarder struct {
	ctrl     *gomock.Controller
	recorder *MockForwarderMockRecorder
	isgomock struct{}
}

// MockForwarderMockRecorder is the mock recorder for MockForwarder.
type MockForwarderMockRecorder struct {
	mock *MockForwarder
}

// NewMockForwarder creates a new mock instance.
func NewMockForwarder(ctrl *gomock.Controller) *MockForwarder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForwarder) EXPECT() *MockForwarderMockRecorder {
	_ = "STUB: not implemented"

	// Start mocks base method.
	return nil
}

func (m *MockForwarder) Start() error { _ = "STUB: not implemented"; return nil }

// Start indicates an expected call of Start.
func (mr *MockForwarderMockRecorder) Start() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Stop mocks base method.
func (m *MockForwarder) Stop() { _ = "STUB: not implemented"; return }

// Stop indicates an expected call of Stop.
func (mr *MockForwarderMockRecorder) Stop() *gomock.Call { _ = "STUB: not implemented"; return nil }
