// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/kvstoremanager (interfaces: KVStoreManager)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/services/kvstoremanager/mock_kvstoremanager.go -package=mock_kvstoremanager github.com/rudderlabs/rudder-server/services/kvstoremanager KVStoreManager
//

// Package mock_kvstoremanager is a generated GoMock package.
package mock_kvstoremanager

import (
	json "encoding/json"

	gomock "go.uber.org/mock/gomock"
)

// MockKVStoreManager is a mock of KVStoreManager interface.
type MockKVStoreManager struct {
	ctrl     *gomock.Controller
	recorder *MockKVStoreManagerMockRecorder
	isgomock struct{}
}

// MockKVStoreManagerMockRecorder is the mock recorder for MockKVStoreManager.
type MockKVStoreManagerMockRecorder struct {
	mock *MockKVStoreManager
}

// NewMockKVStoreManager creates a new mock instance.
func NewMockKVStoreManager(ctrl *gomock.Controller) *MockKVStoreManager {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKVStoreManager) EXPECT() *MockKVStoreManagerMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockKVStoreManager) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockKVStoreManagerMockRecorder) Close() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateClient mocks base method.
func (m *MockKVStoreManager) CreateClient() { _ = "STUB: not implemented"; return }

// CreateClient indicates an expected call of CreateClient.
func (mr *MockKVStoreManagerMockRecorder) CreateClient() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteKey mocks base method.
func (m *MockKVStoreManager) DeleteKey(key string) error { _ = "STUB: not implemented"; return nil }

// DeleteKey indicates an expected call of DeleteKey.
func (mr *MockKVStoreManagerMockRecorder) DeleteKey(key any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HGetAll mocks base method.
func (m *MockKVStoreManager) HGetAll(key string) (map[string]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HGetAll indicates an expected call of HGetAll.
func (mr *MockKVStoreManagerMockRecorder) HGetAll(key any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HMGet mocks base method.
func (m *MockKVStoreManager) HMGet(key string, fields ...string) ([]any, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HMGet indicates an expected call of HMGet.
func (mr *MockKVStoreManagerMockRecorder) HMGet(key any, fields ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HMSet mocks base method.
func (m *MockKVStoreManager) HMSet(key string, fields map[string]any) error {
	_ = "STUB: not implemented"
	return nil
}

// HMSet indicates an expected call of HMSet.
func (mr *MockKVStoreManagerMockRecorder) HMSet(key, fields any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HSet mocks base method.
func (m *MockKVStoreManager) HSet(key, field string, value any) error {
	_ = "STUB: not implemented"
	return nil
}

// HSet indicates an expected call of HSet.
func (mr *MockKVStoreManagerMockRecorder) HSet(key, field, value any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendDataAsJSON mocks base method.
func (m *MockKVStoreManager) SendDataAsJSON(jsonData json.RawMessage, config map[string]any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// SendDataAsJSON indicates an expected call of SendDataAsJSON.
func (mr *MockKVStoreManagerMockRecorder) SendDataAsJSON(jsonData, config any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ShouldSendDataAsJSON mocks base method.
func (m *MockKVStoreManager) ShouldSendDataAsJSON(config map[string]any) bool {
	_ = "STUB: not implemented"
	return false
}

// ShouldSendDataAsJSON indicates an expected call of ShouldSendDataAsJSON.
func (mr *MockKVStoreManagerMockRecorder) ShouldSendDataAsJSON(config any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StatusCode mocks base method.
func (m *MockKVStoreManager) StatusCode(err error) int { _ = "STUB: not implemented"; return 0 }

// StatusCode indicates an expected call of StatusCode.
func (mr *MockKVStoreManagerMockRecorder) StatusCode(err any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
