// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: proto/warehouse/warehouse.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Warehouse_GetHealth_FullMethodName                                            = "/proto.Warehouse/GetHealth"
	Warehouse_GetWHUploads_FullMethodName                                         = "/proto.Warehouse/GetWHUploads"
	Warehouse_GetWHUpload_FullMethodName                                          = "/proto.Warehouse/GetWHUpload"
	Warehouse_TriggerWHUpload_FullMethodName                                      = "/proto.Warehouse/TriggerWHUpload"
	Warehouse_TriggerWHUploads_FullMethodName                                     = "/proto.Warehouse/TriggerWHUploads"
	Warehouse_Validate_FullMethodName                                             = "/proto.Warehouse/Validate"
	Warehouse_RetryWHUploads_FullMethodName                                       = "/proto.Warehouse/RetryWHUploads"
	Warehouse_CountWHUploadsToRetry_FullMethodName                                = "/proto.Warehouse/CountWHUploadsToRetry"
	Warehouse_ValidateObjectStorageDestination_FullMethodName                     = "/proto.Warehouse/ValidateObjectStorageDestination"
	Warehouse_RetrieveFailedBatches_FullMethodName                                = "/proto.Warehouse/RetrieveFailedBatches"
	Warehouse_RetryFailedBatches_FullMethodName                                   = "/proto.Warehouse/RetryFailedBatches"
	Warehouse_GetFirstAbortedUploadInContinuousAbortsByDestination_FullMethodName = "/proto.Warehouse/GetFirstAbortedUploadInContinuousAbortsByDestination"
	Warehouse_GetSyncLatency_FullMethodName                                       = "/proto.Warehouse/GetSyncLatency"
	Warehouse_SyncWHSchema_FullMethodName                                         = "/proto.Warehouse/SyncWHSchema"
	Warehouse_GetDestinationNamespaces_FullMethodName                             = "/proto.Warehouse/GetDestinationNamespaces"
)

// WarehouseClient is the client API for Warehouse service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WarehouseClient interface {
	GetHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error)
	GetWHUploads(ctx context.Context, in *WHUploadsRequest, opts ...grpc.CallOption) (*WHUploadsResponse, error)
	GetWHUpload(ctx context.Context, in *WHUploadRequest, opts ...grpc.CallOption) (*WHUploadResponse, error)
	TriggerWHUpload(ctx context.Context, in *WHUploadRequest, opts ...grpc.CallOption) (*TriggerWhUploadsResponse, error)
	TriggerWHUploads(ctx context.Context, in *WHUploadsRequest, opts ...grpc.CallOption) (*TriggerWhUploadsResponse, error)
	Validate(ctx context.Context, in *WHValidationRequest, opts ...grpc.CallOption) (*WHValidationResponse, error)
	RetryWHUploads(ctx context.Context, in *RetryWHUploadsRequest, opts ...grpc.CallOption) (*RetryWHUploadsResponse, error)
	CountWHUploadsToRetry(ctx context.Context, in *RetryWHUploadsRequest, opts ...grpc.CallOption) (*RetryWHUploadsResponse, error)
	ValidateObjectStorageDestination(ctx context.Context, in *ValidateObjectStorageRequest, opts ...grpc.CallOption) (*ValidateObjectStorageResponse, error)
	RetrieveFailedBatches(ctx context.Context, in *RetrieveFailedBatchesRequest, opts ...grpc.CallOption) (*RetrieveFailedBatchesResponse, error)
	RetryFailedBatches(ctx context.Context, in *RetryFailedBatchesRequest, opts ...grpc.CallOption) (*RetryFailedBatchesResponse, error)
	GetFirstAbortedUploadInContinuousAbortsByDestination(ctx context.Context, in *FirstAbortedUploadInContinuousAbortsByDestinationRequest, opts ...grpc.CallOption) (*FirstAbortedUploadInContinuousAbortsByDestinationResponse, error)
	GetSyncLatency(ctx context.Context, in *SyncLatencyRequest, opts ...grpc.CallOption) (*SyncLatencyResponse, error)
	SyncWHSchema(ctx context.Context, in *SyncWHSchemaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetDestinationNamespaces(ctx context.Context, in *GetDestinationNamespacesRequest, opts ...grpc.CallOption) (*GetDestinationNamespacesResponse, error)
}

type warehouseClient struct {
	cc grpc.ClientConnInterface
}

func NewWarehouseClient(cc grpc.ClientConnInterface) WarehouseClient {
	_ = "STUB: not implemented"
	return *new(WarehouseClient)
}

func (c *warehouseClient) GetHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *warehouseClient) GetWHUploads(ctx context.Context, in *WHUploadsRequest, opts ...grpc.CallOption) (*WHUploadsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *warehouseClient) GetWHUpload(ctx context.Context, in *WHUploadRequest, opts ...grpc.CallOption) (*WHUploadResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *warehouseClient) TriggerWHUpload(ctx context.Context, in *WHUploadRequest, opts ...grpc.CallOption) (*TriggerWhUploadsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *warehouseClient) TriggerWHUploads(ctx context.Context, in *WHUploadsRequest, opts ...grpc.CallOption) (*TriggerWhUploadsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *warehouseClient) Validate(ctx context.Context, in *WHValidationRequest, opts ...grpc.CallOption) (*WHValidationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *warehouseClient) RetryWHUploads(ctx context.Context, in *RetryWHUploadsRequest, opts ...grpc.CallOption) (*RetryWHUploadsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *warehouseClient) CountWHUploadsToRetry(ctx context.Context, in *RetryWHUploadsRequest, opts ...grpc.CallOption) (*RetryWHUploadsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *warehouseClient) ValidateObjectStorageDestination(ctx context.Context, in *ValidateObjectStorageRequest, opts ...grpc.CallOption) (*ValidateObjectStorageResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *warehouseClient) RetrieveFailedBatches(ctx context.Context, in *RetrieveFailedBatchesRequest, opts ...grpc.CallOption) (*RetrieveFailedBatchesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *warehouseClient) RetryFailedBatches(ctx context.Context, in *RetryFailedBatchesRequest, opts ...grpc.CallOption) (*RetryFailedBatchesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *warehouseClient) GetFirstAbortedUploadInContinuousAbortsByDestination(ctx context.Context, in *FirstAbortedUploadInContinuousAbortsByDestinationRequest, opts ...grpc.CallOption) (*FirstAbortedUploadInContinuousAbortsByDestinationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *warehouseClient) GetSyncLatency(ctx context.Context, in *SyncLatencyRequest, opts ...grpc.CallOption) (*SyncLatencyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *warehouseClient) SyncWHSchema(ctx context.Context, in *SyncWHSchemaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *warehouseClient) GetDestinationNamespaces(ctx context.Context, in *GetDestinationNamespacesRequest, opts ...grpc.CallOption) (*GetDestinationNamespacesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// WarehouseServer is the server API for Warehouse service.
// All implementations must embed UnimplementedWarehouseServer
// for forward compatibility
type WarehouseServer interface {
	GetHealth(context.Context, *emptypb.Empty) (*wrapperspb.BoolValue, error)
	GetWHUploads(context.Context, *WHUploadsRequest) (*WHUploadsResponse, error)
	GetWHUpload(context.Context, *WHUploadRequest) (*WHUploadResponse, error)
	TriggerWHUpload(context.Context, *WHUploadRequest) (*TriggerWhUploadsResponse, error)
	TriggerWHUploads(context.Context, *WHUploadsRequest) (*TriggerWhUploadsResponse, error)
	Validate(context.Context, *WHValidationRequest) (*WHValidationResponse, error)
	RetryWHUploads(context.Context, *RetryWHUploadsRequest) (*RetryWHUploadsResponse, error)
	CountWHUploadsToRetry(context.Context, *RetryWHUploadsRequest) (*RetryWHUploadsResponse, error)
	ValidateObjectStorageDestination(context.Context, *ValidateObjectStorageRequest) (*ValidateObjectStorageResponse, error)
	RetrieveFailedBatches(context.Context, *RetrieveFailedBatchesRequest) (*RetrieveFailedBatchesResponse, error)
	RetryFailedBatches(context.Context, *RetryFailedBatchesRequest) (*RetryFailedBatchesResponse, error)
	GetFirstAbortedUploadInContinuousAbortsByDestination(context.Context, *FirstAbortedUploadInContinuousAbortsByDestinationRequest) (*FirstAbortedUploadInContinuousAbortsByDestinationResponse, error)
	GetSyncLatency(context.Context, *SyncLatencyRequest) (*SyncLatencyResponse, error)
	SyncWHSchema(context.Context, *SyncWHSchemaRequest) (*emptypb.Empty, error)
	GetDestinationNamespaces(context.Context, *GetDestinationNamespacesRequest) (*GetDestinationNamespacesResponse, error)
	mustEmbedUnimplementedWarehouseServer()
}

// UnimplementedWarehouseServer must be embedded to have forward compatible implementations.
type UnimplementedWarehouseServer struct {
}

func (UnimplementedWarehouseServer) GetHealth(context.Context, *emptypb.Empty) (*wrapperspb.BoolValue, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedWarehouseServer) GetWHUploads(context.Context, *WHUploadsRequest) (*WHUploadsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedWarehouseServer) GetWHUpload(context.Context, *WHUploadRequest) (*WHUploadResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedWarehouseServer) TriggerWHUpload(context.Context, *WHUploadRequest) (*TriggerWhUploadsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedWarehouseServer) TriggerWHUploads(context.Context, *WHUploadsRequest) (*TriggerWhUploadsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedWarehouseServer) Validate(context.Context, *WHValidationRequest) (*WHValidationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedWarehouseServer) RetryWHUploads(context.Context, *RetryWHUploadsRequest) (*RetryWHUploadsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedWarehouseServer) CountWHUploadsToRetry(context.Context, *RetryWHUploadsRequest) (*RetryWHUploadsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedWarehouseServer) ValidateObjectStorageDestination(context.Context, *ValidateObjectStorageRequest) (*ValidateObjectStorageResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedWarehouseServer) RetrieveFailedBatches(context.Context, *RetrieveFailedBatchesRequest) (*RetrieveFailedBatchesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedWarehouseServer) RetryFailedBatches(context.Context, *RetryFailedBatchesRequest) (*RetryFailedBatchesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedWarehouseServer) GetFirstAbortedUploadInContinuousAbortsByDestination(context.Context, *FirstAbortedUploadInContinuousAbortsByDestinationRequest) (*FirstAbortedUploadInContinuousAbortsByDestinationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedWarehouseServer) GetSyncLatency(context.Context, *SyncLatencyRequest) (*SyncLatencyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedWarehouseServer) SyncWHSchema(context.Context, *SyncWHSchemaRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedWarehouseServer) GetDestinationNamespaces(context.Context, *GetDestinationNamespacesRequest) (*GetDestinationNamespacesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedWarehouseServer) mustEmbedUnimplementedWarehouseServer() {
	_ = "STUB: not implemented"

	// UnsafeWarehouseServer may be embedded to opt out of forward compatibility for this service.
	// Use of this interface is not recommended, as added methods to WarehouseServer will
	// result in compilation errors.
	return
}

type UnsafeWarehouseServer interface {
	mustEmbedUnimplementedWarehouseServer()
}

func RegisterWarehouseServer(s grpc.ServiceRegistrar, srv WarehouseServer) {
	_ = "STUB: not implemented"
	return
}

func _Warehouse_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Warehouse_GetWHUploads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Warehouse_GetWHUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Warehouse_TriggerWHUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Warehouse_TriggerWHUploads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Warehouse_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Warehouse_RetryWHUploads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Warehouse_CountWHUploadsToRetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Warehouse_ValidateObjectStorageDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Warehouse_RetrieveFailedBatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Warehouse_RetryFailedBatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Warehouse_GetFirstAbortedUploadInContinuousAbortsByDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Warehouse_GetSyncLatency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Warehouse_SyncWHSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Warehouse_GetDestinationNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Warehouse_ServiceDesc is the grpc.ServiceDesc for Warehouse service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Warehouse_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Warehouse",
	HandlerType: (*WarehouseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _Warehouse_GetHealth_Handler,
		},
		{
			MethodName: "GetWHUploads",
			Handler:    _Warehouse_GetWHUploads_Handler,
		},
		{
			MethodName: "GetWHUpload",
			Handler:    _Warehouse_GetWHUpload_Handler,
		},
		{
			MethodName: "TriggerWHUpload",
			Handler:    _Warehouse_TriggerWHUpload_Handler,
		},
		{
			MethodName: "TriggerWHUploads",
			Handler:    _Warehouse_TriggerWHUploads_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _Warehouse_Validate_Handler,
		},
		{
			MethodName: "RetryWHUploads",
			Handler:    _Warehouse_RetryWHUploads_Handler,
		},
		{
			MethodName: "CountWHUploadsToRetry",
			Handler:    _Warehouse_CountWHUploadsToRetry_Handler,
		},
		{
			MethodName: "ValidateObjectStorageDestination",
			Handler:    _Warehouse_ValidateObjectStorageDestination_Handler,
		},
		{
			MethodName: "RetrieveFailedBatches",
			Handler:    _Warehouse_RetrieveFailedBatches_Handler,
		},
		{
			MethodName: "RetryFailedBatches",
			Handler:    _Warehouse_RetryFailedBatches_Handler,
		},
		{
			MethodName: "GetFirstAbortedUploadInContinuousAbortsByDestination",
			Handler:    _Warehouse_GetFirstAbortedUploadInContinuousAbortsByDestination_Handler,
		},
		{
			MethodName: "GetSyncLatency",
			Handler:    _Warehouse_GetSyncLatency_Handler,
		},
		{
			MethodName: "SyncWHSchema",
			Handler:    _Warehouse_SyncWHSchema_Handler,
		},
		{
			MethodName: "GetDestinationNamespaces",
			Handler:    _Warehouse_GetDestinationNamespaces_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/warehouse/warehouse.proto",
}
