// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/internal/transformer-client (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/transformer-client/mock_transformer_client.go -package=mocks_transformer_client github.com/rudderlabs/rudder-server/internal/transformer-client Client
//

// Package mocks_transformer_client is a generated GoMock package.
package mocks_transformer_client

import (
	http "net/http"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	_ = "STUB: not implemented"

	// Do mocks base method.
	return nil
}

func (m *MockClient) Do(req *http.Request) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Do indicates an expected call of Do.
func (mr *MockClientMockRecorder) Do(req any) *gomock.Call { _ = "STUB: not implemented"; return nil }
