// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/backend-config (interfaces: BackendConfig)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/backend-config/mock_backendconfig.go -package=mock_backendconfig github.com/rudderlabs/rudder-server/backend-config BackendConfig
//

// Package mock_backendconfig is a generated GoMock package.
package mock_backendconfig

import (
	context "context"

	backendconfig "github.com/rudderlabs/rudder-server/backend-config"
	identity "github.com/rudderlabs/rudder-server/services/controlplane/identity"
	pubsub "github.com/rudderlabs/rudder-server/utils/pubsub"
	gomock "go.uber.org/mock/gomock"
)

// MockBackendConfig is a mock of BackendConfig interface.
type MockBackendConfig struct {
	ctrl     *gomock.Controller
	recorder *MockBackendConfigMockRecorder
	isgomock struct{}
}

// MockBackendConfigMockRecorder is the mock recorder for MockBackendConfig.
type MockBackendConfigMockRecorder struct {
	mock *MockBackendConfig
}

// NewMockBackendConfig creates a new mock instance.
func NewMockBackendConfig(ctrl *gomock.Controller) *MockBackendConfig {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendConfig) EXPECT() *MockBackendConfigMockRecorder {
	_ = "STUB: not implemented"

	// AccessToken mocks base method.
	return nil
}

func (m *MockBackendConfig) AccessToken() string { _ = "STUB: not implemented"; return "" }

// AccessToken indicates an expected call of AccessToken.
func (mr *MockBackendConfigMockRecorder) AccessToken() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Get mocks base method.
func (m *MockBackendConfig) Get(arg0 context.Context) (map[string]backendconfig.ConfigT, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Get indicates an expected call of Get.
func (mr *MockBackendConfigMockRecorder) Get(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Identity mocks base method.
func (m *MockBackendConfig) Identity() identity.Identifier {
	_ = "STUB: not implemented"
	return *new(identity.Identifier)
}

// Identity indicates an expected call of Identity.
func (mr *MockBackendConfigMockRecorder) Identity() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetUp mocks base method.
func (m *MockBackendConfig) SetUp() error { _ = "STUB: not implemented"; return nil }

// SetUp indicates an expected call of SetUp.
func (mr *MockBackendConfigMockRecorder) SetUp() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StartWithIDs mocks base method.
func (m *MockBackendConfig) StartWithIDs(ctx context.Context, workspaces string) {
	_ = "STUB: not implemented"
	return
}

// StartWithIDs indicates an expected call of StartWithIDs.
func (mr *MockBackendConfigMockRecorder) StartWithIDs(ctx, workspaces any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stop mocks base method.
func (m *MockBackendConfig) Stop() { _ = "STUB: not implemented"; return }

// Stop indicates an expected call of Stop.
func (mr *MockBackendConfigMockRecorder) Stop() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Subscribe mocks base method.
func (m *MockBackendConfig) Subscribe(ctx context.Context, topic backendconfig.Topic) pubsub.DataChannel {
	_ = "STUB: not implemented"
	return *new(pubsub.DataChannel)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockBackendConfigMockRecorder) Subscribe(ctx, topic any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WaitForConfig mocks base method.
func (m *MockBackendConfig) WaitForConfig(ctx context.Context) { _ = "STUB: not implemented"; return }

// WaitForConfig indicates an expected call of WaitForConfig.
func (mr *MockBackendConfigMockRecorder) WaitForConfig(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
