// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/warehouse/utils (interfaces: Uploader)
//
// Generated by this command:
//
//	mockgen -destination=../internal/mocks/utils/mock_uploader.go -package mock_uploader github.com/rudderlabs/rudder-server/warehouse/utils Uploader
//

// Package mock_uploader is a generated GoMock package.
package mock_uploader

import (
	context "context"

	model "github.com/rudderlabs/rudder-server/warehouse/internal/model"
	warehouseutils "github.com/rudderlabs/rudder-server/warehouse/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockUploader is a mock of Uploader interface.
type MockUploader struct {
	ctrl     *gomock.Controller
	recorder *MockUploaderMockRecorder
	isgomock struct{}
}

// MockUploaderMockRecorder is the mock recorder for MockUploader.
type MockUploaderMockRecorder struct {
	mock *MockUploader
}

// NewMockUploader creates a new mock instance.
func NewMockUploader(ctrl *gomock.Controller) *MockUploader { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploader) EXPECT() *MockUploaderMockRecorder {
	_ = "STUB: not implemented"

	// CanAppend mocks base method.
	return nil
}

func (m *MockUploader) CanAppend() bool { _ = "STUB: not implemented"; return false }

// CanAppend indicates an expected call of CanAppend.
func (mr *MockUploaderMockRecorder) CanAppend() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetLoadFileType mocks base method.
func (m *MockUploader) GetLoadFileType() string { _ = "STUB: not implemented"; return "" }

// GetLoadFileType indicates an expected call of GetLoadFileType.
func (mr *MockUploaderMockRecorder) GetLoadFileType() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLoadFilesMetadata mocks base method.
func (m *MockUploader) GetLoadFilesMetadata(ctx context.Context, options warehouseutils.GetLoadFilesOptions) ([]warehouseutils.LoadFile, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetLoadFilesMetadata indicates an expected call of GetLoadFilesMetadata.
func (mr *MockUploaderMockRecorder) GetLoadFilesMetadata(ctx, options any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLocalSchema mocks base method.
func (m *MockUploader) GetLocalSchema(ctx context.Context) (model.Schema, error) {
	_ = "STUB: not implemented"
	return *new(model.Schema), nil
}

// GetLocalSchema indicates an expected call of GetLocalSchema.
func (mr *MockUploaderMockRecorder) GetLocalSchema(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSampleLoadFileLocation mocks base method.
func (m *MockUploader) GetSampleLoadFileLocation(ctx context.Context, tableName string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetSampleLoadFileLocation indicates an expected call of GetSampleLoadFileLocation.
func (mr *MockUploaderMockRecorder) GetSampleLoadFileLocation(ctx, tableName any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSingleLoadFile mocks base method.
func (m *MockUploader) GetSingleLoadFile(ctx context.Context, tableName string) (warehouseutils.LoadFile, error) {
	_ = "STUB: not implemented"
	return *new(warehouseutils.LoadFile), nil
}

// GetSingleLoadFile indicates an expected call of GetSingleLoadFile.
func (mr *MockUploaderMockRecorder) GetSingleLoadFile(ctx, tableName any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetTableSchemaInUpload mocks base method.
func (m *MockUploader) GetTableSchemaInUpload(tableName string) model.TableSchema {
	_ = "STUB: not implemented"
	return *new(model.TableSchema)
}

// GetTableSchemaInUpload indicates an expected call of GetTableSchemaInUpload.
func (mr *MockUploaderMockRecorder) GetTableSchemaInUpload(tableName any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetTableSchemaInWarehouse mocks base method.
func (m *MockUploader) GetTableSchemaInWarehouse(tableName string) model.TableSchema {
	_ = "STUB: not implemented"
	return *new(model.TableSchema)
}

// GetTableSchemaInWarehouse indicates an expected call of GetTableSchemaInWarehouse.
func (mr *MockUploaderMockRecorder) GetTableSchemaInWarehouse(tableName any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsWarehouseSchemaEmpty mocks base method.
func (m *MockUploader) IsWarehouseSchemaEmpty() bool { _ = "STUB: not implemented"; return false }

// IsWarehouseSchemaEmpty indicates an expected call of IsWarehouseSchemaEmpty.
func (mr *MockUploaderMockRecorder) IsWarehouseSchemaEmpty() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ShouldOnDedupUseNewRecord mocks base method.
func (m *MockUploader) ShouldOnDedupUseNewRecord() bool { _ = "STUB: not implemented"; return false }

// ShouldOnDedupUseNewRecord indicates an expected call of ShouldOnDedupUseNewRecord.
func (mr *MockUploaderMockRecorder) ShouldOnDedupUseNewRecord() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateLocalSchema mocks base method.
func (m *MockUploader) UpdateLocalSchema(ctx context.Context, schema model.Schema) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateLocalSchema indicates an expected call of UpdateLocalSchema.
func (mr *MockUploaderMockRecorder) UpdateLocalSchema(ctx, schema any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UseRudderStorage mocks base method.
func (m *MockUploader) UseRudderStorage() bool { _ = "STUB: not implemented"; return false }

// UseRudderStorage indicates an expected call of UseRudderStorage.
func (mr *MockUploaderMockRecorder) UseRudderStorage() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
