// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: proto/common/dpauth.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DPAuthService_GetConnectionToken_FullMethodName = "/proto.DPAuthService/GetConnectionToken"
	DPAuthService_GetWorkspaceToken_FullMethodName  = "/proto.DPAuthService/GetWorkspaceToken"
)

// DPAuthServiceClient is the client API for DPAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DPAuthServiceClient interface {
	GetConnectionToken(ctx context.Context, in *GetConnectionTokenRequest, opts ...grpc.CallOption) (*GetConnectionTokenResponse, error)
	GetWorkspaceToken(ctx context.Context, in *GetWorkspaceTokenRequest, opts ...grpc.CallOption) (*GetWorkspaceTokenResponse, error)
}

type dPAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDPAuthServiceClient(cc grpc.ClientConnInterface) DPAuthServiceClient {
	_ = "STUB: not implemented"
	return *new(DPAuthServiceClient)
}

func (c *dPAuthServiceClient) GetConnectionToken(ctx context.Context, in *GetConnectionTokenRequest, opts ...grpc.CallOption) (*GetConnectionTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *dPAuthServiceClient) GetWorkspaceToken(ctx context.Context, in *GetWorkspaceTokenRequest, opts ...grpc.CallOption) (*GetWorkspaceTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DPAuthServiceServer is the server API for DPAuthService service.
// All implementations must embed UnimplementedDPAuthServiceServer
// for forward compatibility
type DPAuthServiceServer interface {
	GetConnectionToken(context.Context, *GetConnectionTokenRequest) (*GetConnectionTokenResponse, error)
	GetWorkspaceToken(context.Context, *GetWorkspaceTokenRequest) (*GetWorkspaceTokenResponse, error)
	mustEmbedUnimplementedDPAuthServiceServer()
}

// UnimplementedDPAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDPAuthServiceServer struct {
}

func (UnimplementedDPAuthServiceServer) GetConnectionToken(context.Context, *GetConnectionTokenRequest) (*GetConnectionTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedDPAuthServiceServer) GetWorkspaceToken(context.Context, *GetWorkspaceTokenRequest) (*GetWorkspaceTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedDPAuthServiceServer) mustEmbedUnimplementedDPAuthServiceServer() {
	_ = "STUB: not implemented"

	// UnsafeDPAuthServiceServer may be embedded to opt out of forward compatibility for this service.
	// Use of this interface is not recommended, as added methods to DPAuthServiceServer will
	// result in compilation errors.
	return
}

type UnsafeDPAuthServiceServer interface {
	mustEmbedUnimplementedDPAuthServiceServer()
}

func RegisterDPAuthServiceServer(s grpc.ServiceRegistrar, srv DPAuthServiceServer) {
	_ = "STUB: not implemented"
	return
}

func _DPAuthService_GetConnectionToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _DPAuthService_GetWorkspaceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DPAuthService_ServiceDesc is the grpc.ServiceDesc for DPAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DPAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DPAuthService",
	HandlerType: (*DPAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConnectionToken",
			Handler:    _DPAuthService_GetConnectionToken_Handler,
		},
		{
			MethodName: "GetWorkspaceToken",
			Handler:    _DPAuthService_GetWorkspaceToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/common/dpauth.proto",
}
