// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/lytics_bulk_upload (interfaces: LyticsService)
//
// Generated by this command:
//
//	mockgen -destination=./lytics_bulk_upload_mock.go -package=mocks github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/lytics_bulk_upload LyticsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	lyticsBulkUpload "github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/lytics_bulk_upload"
	gomock "go.uber.org/mock/gomock"
)

// MockLyticsService is a mock of LyticsService interface.
type MockLyticsService struct {
	ctrl     *gomock.Controller
	recorder *MockLyticsServiceMockRecorder
}

// MockLyticsServiceMockRecorder is the mock recorder for MockLyticsService.
type MockLyticsServiceMockRecorder struct {
	mock *MockLyticsService
}

// NewMockLyticsService creates a new mock instance.
func NewMockLyticsService(ctrl *gomock.Controller) *MockLyticsService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLyticsService) EXPECT() *MockLyticsServiceMockRecorder {
	_ = "STUB: not implemented"

	// MakeHTTPRequest mocks base method.
	return nil
}

func (m *MockLyticsService) MakeHTTPRequest(arg0 *lyticsBulkUpload.HttpRequestData) ([]byte, int, error) {
	_ = "STUB: not implemented"
	return nil, 0, nil
}

// MakeHTTPRequest indicates an expected call of MakeHTTPRequest.
func (mr *MockLyticsServiceMockRecorder) MakeHTTPRequest(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UploadBulkFile mocks base method.
func (m *MockLyticsService) UploadBulkFile(arg0 *lyticsBulkUpload.HttpRequestData, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// UploadBulkFile indicates an expected call of UploadBulkFile.
func (mr *MockLyticsServiceMockRecorder) UploadBulkFile(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
