// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/streammanager/personalize (interfaces: PersonalizeClient)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=../../../mocks/services/streammanager/personalize/mock_personalize.go -package mock_personalize github.com/rudderlabs/rudder-server/services/streammanager/personalize PersonalizeClient
//

// Package mock_personalize is a generated GoMock package.
package mock_personalize

import (
	context "context"

	personalizeevents "github.com/aws/aws-sdk-go-v2/service/personalizeevents"
	gomock "go.uber.org/mock/gomock"
)

// MockPersonalizeClient is a mock of PersonalizeClient interface.
type MockPersonalizeClient struct {
	ctrl     *gomock.Controller
	recorder *MockPersonalizeClientMockRecorder
	isgomock struct{}
}

// MockPersonalizeClientMockRecorder is the mock recorder for MockPersonalizeClient.
type MockPersonalizeClientMockRecorder struct {
	mock *MockPersonalizeClient
}

// NewMockPersonalizeClient creates a new mock instance.
func NewMockPersonalizeClient(ctrl *gomock.Controller) *MockPersonalizeClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonalizeClient) EXPECT() *MockPersonalizeClientMockRecorder {
	_ = "STUB: not implemented"

	// PutEvents mocks base method.
	return nil
}

func (m *MockPersonalizeClient) PutEvents(ctx context.Context, input *personalizeevents.PutEventsInput, opts ...func(*personalizeevents.Options)) (*personalizeevents.PutEventsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutEvents indicates an expected call of PutEvents.
func (mr *MockPersonalizeClientMockRecorder) PutEvents(ctx, input any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PutItems mocks base method.
func (m *MockPersonalizeClient) PutItems(ctx context.Context, input *personalizeevents.PutItemsInput, opts ...func(*personalizeevents.Options)) (*personalizeevents.PutItemsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutItems indicates an expected call of PutItems.
func (mr *MockPersonalizeClientMockRecorder) PutItems(ctx, input any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PutUsers mocks base method.
func (m *MockPersonalizeClient) PutUsers(ctx context.Context, input *personalizeevents.PutUsersInput, opts ...func(*personalizeevents.Options)) (*personalizeevents.PutUsersOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutUsers indicates an expected call of PutUsers.
func (mr *MockPersonalizeClientMockRecorder) PutUsers(ctx, input any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
