// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/enterprise/reporting (interfaces: ErrorNormalizer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/enterprise/reporting/mock_error_normalizer.go -package=mocks github.com/rudderlabs/rudder-server/enterprise/reporting ErrorNormalizer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	types "github.com/rudderlabs/rudder-server/utils/types"
	gomock "go.uber.org/mock/gomock"
)

// MockErrorNormalizer is a mock of ErrorNormalizer interface.
type MockErrorNormalizer struct {
	ctrl     *gomock.Controller
	recorder *MockErrorNormalizerMockRecorder
	isgomock struct{}
}

// MockErrorNormalizerMockRecorder is the mock recorder for MockErrorNormalizer.
type MockErrorNormalizerMockRecorder struct {
	mock *MockErrorNormalizer
}

// NewMockErrorNormalizer creates a new mock instance.
func NewMockErrorNormalizer(ctrl *gomock.Controller) *MockErrorNormalizer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErrorNormalizer) EXPECT() *MockErrorNormalizerMockRecorder {
	_ = "STUB: not implemented"

	// NormalizeError mocks base method.
	return nil
}

func (m *MockErrorNormalizer) NormalizeError(ctx context.Context, errorDetailGroupKey types.ErrorDetailGroupKey, errorMessage string) string {
	_ = "STUB: not implemented"
	return ""
}

// NormalizeError indicates an expected call of NormalizeError.
func (mr *MockErrorNormalizerMockRecorder) NormalizeError(ctx, errorDetailGroupKey, errorMessage any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StartCleanup mocks base method.
func (m *MockErrorNormalizer) StartCleanup(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// StartCleanup indicates an expected call of StartCleanup.
func (mr *MockErrorNormalizerMockRecorder) StartCleanup(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
