// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/debugger (interfaces: TransformerAny)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/services/debugger/uploader.go -package mock_debugger github.com/rudderlabs/rudder-server/services/debugger TransformerAny
//

// Package mock_debugger is a generated GoMock package.
package mock_debugger

import (
	gomock "go.uber.org/mock/gomock"
)

// MockTransformerAny is a mock of TransformerAny interface.
type MockTransformerAny struct {
	ctrl     *gomock.Controller
	recorder *MockTransformerAnyMockRecorder
	isgomock struct{}
}

// MockTransformerAnyMockRecorder is the mock recorder for MockTransformerAny.
type MockTransformerAnyMockRecorder struct {
	mock *MockTransformerAny
}

// NewMockTransformerAny creates a new mock instance.
func NewMockTransformerAny(ctrl *gomock.Controller) *MockTransformerAny {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransformerAny) EXPECT() *MockTransformerAnyMockRecorder {
	_ = "STUB: not implemented"

	// Transform mocks base method.
	return nil
}

func (m *MockTransformerAny) Transform(data []any) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Transform indicates an expected call of Transform.
func (mr *MockTransformerAnyMockRecorder) Transform(data any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
