// Code generated by MockGen. DO NOT EDIT.
// Source: ./aggregator.go
//
// Generated by this command:
//
//	mockgen -destination=./aggregator_mock.go -package=aggregator -source=./aggregator.go Aggregator
//

// Package aggregator is a generated GoMock package.
package aggregator

import (
	context "context"
	json "encoding/json"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockAggregator is a mock of Aggregator interface.
type MockAggregator struct {
	ctrl     *gomock.Controller
	recorder *MockAggregatorMockRecorder
	isgomock struct{}
}

// MockAggregatorMockRecorder is the mock recorder for MockAggregator.
type MockAggregatorMockRecorder struct {
	mock *MockAggregator
}

// NewMockAggregator creates a new mock instance.
func NewMockAggregator(ctrl *gomock.Controller) *MockAggregator {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregator) EXPECT() *MockAggregatorMockRecorder {
	_ = "STUB: not implemented"

	// Aggregate mocks base method.
	return nil
}

func (m *MockAggregator) Aggregate(ctx context.Context, start, end time.Time) ([]json.RawMessage, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Aggregate indicates an expected call of Aggregate.
func (mr *MockAggregatorMockRecorder) Aggregate(ctx, start, end any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
