// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: proto/cluster/cluster.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PartitionMigration_StreamJobs_FullMethodName = "/proto.PartitionMigration/StreamJobs"
)

// PartitionMigrationClient is the client API for PartitionMigration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartitionMigrationClient interface {
	// Bidirectional streaming RPC for migrating jobs in batches
	StreamJobs(ctx context.Context, opts ...grpc.CallOption) (PartitionMigration_StreamJobsClient, error)
}

type partitionMigrationClient struct {
	cc grpc.ClientConnInterface
}

func NewPartitionMigrationClient(cc grpc.ClientConnInterface) PartitionMigrationClient {
	_ = "STUB: not implemented"
	return *new(PartitionMigrationClient)
}

func (c *partitionMigrationClient) StreamJobs(ctx context.Context, opts ...grpc.CallOption) (PartitionMigration_StreamJobsClient, error) {
	_ = "STUB: not implemented"
	return *new(PartitionMigration_StreamJobsClient), nil
}

type PartitionMigration_StreamJobsClient interface {
	Send(*StreamJobsRequest) error
	Recv() (*JobsBatchAck, error)
	grpc.ClientStream
}

type partitionMigrationStreamJobsClient struct {
	grpc.ClientStream
}

func (x *partitionMigrationStreamJobsClient) Send(m *StreamJobsRequest) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *partitionMigrationStreamJobsClient) Recv() (*JobsBatchAck, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PartitionMigrationServer is the server API for PartitionMigration service.
// All implementations must embed UnimplementedPartitionMigrationServer
// for forward compatibility
type PartitionMigrationServer interface {
	// Bidirectional streaming RPC for migrating jobs in batches
	StreamJobs(PartitionMigration_StreamJobsServer) error
	mustEmbedUnimplementedPartitionMigrationServer()
}

// UnimplementedPartitionMigrationServer must be embedded to have forward compatible implementations.
type UnimplementedPartitionMigrationServer struct {
}

func (UnimplementedPartitionMigrationServer) StreamJobs(PartitionMigration_StreamJobsServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (UnimplementedPartitionMigrationServer) mustEmbedUnimplementedPartitionMigrationServer() {
	_ = "STUB: not implemented"

	// UnsafePartitionMigrationServer may be embedded to opt out of forward compatibility for this service.
	// Use of this interface is not recommended, as added methods to PartitionMigrationServer will
	// result in compilation errors.
	return
}

type UnsafePartitionMigrationServer interface {
	mustEmbedUnimplementedPartitionMigrationServer()
}

func RegisterPartitionMigrationServer(s grpc.ServiceRegistrar, srv PartitionMigrationServer) {
	_ = "STUB: not implemented"
	return
}

func _PartitionMigration_StreamJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type PartitionMigration_StreamJobsServer interface {
	Send(*JobsBatchAck) error
	Recv() (*StreamJobsRequest, error)
	grpc.ServerStream
}

type partitionMigrationStreamJobsServer struct {
	grpc.ServerStream
}

func (x *partitionMigrationStreamJobsServer) Send(m *JobsBatchAck) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *partitionMigrationStreamJobsServer) Recv() (*StreamJobsRequest, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PartitionMigration_ServiceDesc is the grpc.ServiceDesc for PartitionMigration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartitionMigration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PartitionMigration",
	HandlerType: (*PartitionMigrationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamJobs",
			Handler:       _PartitionMigration_StreamJobs_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/cluster/cluster.proto",
}
