// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/app (interfaces: SuppressUserFeature)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/app/mock_features.go -package=mock_app github.com/rudderlabs/rudder-server/app SuppressUserFeature
//

// Package mock_app is a generated GoMock package.
package mock_app

import (
	context "context"

	backendconfig "github.com/rudderlabs/rudder-server/backend-config"
	types "github.com/rudderlabs/rudder-server/utils/types"
	gomock "go.uber.org/mock/gomock"
)

// MockSuppressUserFeature is a mock of SuppressUserFeature interface.
type MockSuppressUserFeature struct {
	ctrl     *gomock.Controller
	recorder *MockSuppressUserFeatureMockRecorder
	isgomock struct{}
}

// MockSuppressUserFeatureMockRecorder is the mock recorder for MockSuppressUserFeature.
type MockSuppressUserFeatureMockRecorder struct {
	mock *MockSuppressUserFeature
}

// NewMockSuppressUserFeature creates a new mock instance.
func NewMockSuppressUserFeature(ctrl *gomock.Controller) *MockSuppressUserFeature {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuppressUserFeature) EXPECT() *MockSuppressUserFeatureMockRecorder {
	_ = "STUB: not implemented"

	// Setup mocks base method.
	return nil
}

func (m *MockSuppressUserFeature) Setup(ctx context.Context, backendConfig backendconfig.BackendConfig) (types.UserSuppression, error) {
	_ = "STUB: not implemented"
	return *new(types.UserSuppression), nil
}

// Setup indicates an expected call of Setup.
func (mr *MockSuppressUserFeatureMockRecorder) Setup(ctx, backendConfig any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
