// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/app (interfaces: App)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/app/mock_app.go -package=mock_app github.com/rudderlabs/rudder-server/app App
//

// Package mock_app is a generated GoMock package.
package mock_app

import (
	app "github.com/rudderlabs/rudder-server/app"
	gomock "go.uber.org/mock/gomock"
)

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
	isgomock struct{}
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	_ = "STUB: not implemented"

	// Features mocks base method.
	return nil
}

func (m *MockApp) Features() *app.Features { _ = "STUB: not implemented"; return nil }

// Features indicates an expected call of Features.
func (mr *MockAppMockRecorder) Features() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Options mocks base method.
func (m *MockApp) Options() *app.Options { _ = "STUB: not implemented"; return nil }

// Options indicates an expected call of Options.
func (mr *MockAppMockRecorder) Options() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Setup mocks base method.
func (m *MockApp) Setup() { _ = "STUB: not implemented"; return }

// Setup indicates an expected call of Setup.
func (mr *MockAppMockRecorder) Setup() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Stop mocks base method.
func (m *MockApp) Stop() { _ = "STUB: not implemented"; return }

// Stop indicates an expected call of Stop.
func (mr *MockAppMockRecorder) Stop() *gomock.Call { _ = "STUB: not implemented"; return nil }
