// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/utils/sysUtils (interfaces: GZipI)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/utils/sysUtils/mock_compress.go -package mock_sysUtils github.com/rudderlabs/rudder-server/utils/sysUtils GZipI
//

// Package mock_sysUtils is a generated GoMock package.
package mock_sysUtils

import (
	gzip "compress/gzip"
	io "io"

	gomock "go.uber.org/mock/gomock"
)

// MockGZipI is a mock of GZipI interface.
type MockGZipI struct {
	ctrl     *gomock.Controller
	recorder *MockGZipIMockRecorder
	isgomock struct{}
}

// MockGZipIMockRecorder is the mock recorder for MockGZipI.
type MockGZipIMockRecorder struct {
	mock *MockGZipI
}

// NewMockGZipI creates a new mock instance.
func NewMockGZipI(ctrl *gomock.Controller) *MockGZipI { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGZipI) EXPECT() *MockGZipIMockRecorder {
	_ = "STUB: not implemented"

	// NewReader mocks base method.
	return nil
}

func (m *MockGZipI) NewReader(r io.Reader) (*gzip.Reader, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewReader indicates an expected call of NewReader.
func (mr *MockGZipIMockRecorder) NewReader(r any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NewWriter mocks base method.
func (m *MockGZipI) NewWriter(w io.Writer) *gzip.Writer { _ = "STUB: not implemented"; return nil }

// NewWriter indicates an expected call of NewWriter.
func (mr *MockGZipIMockRecorder) NewWriter(w any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
