// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/utils/sysUtils (interfaces: OsI)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/utils/sysUtils/mock_os.go -package mock_sysUtils github.com/rudderlabs/rudder-server/utils/sysUtils OsI
//

// Package mock_sysUtils is a generated GoMock package.
package mock_sysUtils

import (
	os "os"

	gomock "go.uber.org/mock/gomock"
)

// MockOsI is a mock of OsI interface.
type MockOsI struct {
	ctrl     *gomock.Controller
	recorder *MockOsIMockRecorder
	isgomock struct{}
}

// MockOsIMockRecorder is the mock recorder for MockOsI.
type MockOsIMockRecorder struct {
	mock *MockOsI
}

// NewMockOsI creates a new mock instance.
func NewMockOsI(ctrl *gomock.Controller) *MockOsI { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOsI) EXPECT() *MockOsIMockRecorder {
	_ = "STUB: not implemented"

	// Create mocks base method.
	return nil
}

func (m *MockOsI) Create(name string) (*os.File, error) { _ = "STUB: not implemented"; return nil, nil }

// Create indicates an expected call of Create.
func (mr *MockOsIMockRecorder) Create(name any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// Getenv mocks base method.
func (m *MockOsI) Getenv(key string) string { _ = "STUB: not implemented"; return "" }

// Getenv indicates an expected call of Getenv.
func (mr *MockOsIMockRecorder) Getenv(key any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// IsNotExist mocks base method.
func (m *MockOsI) IsNotExist(err error) bool { _ = "STUB: not implemented"; return false }

// IsNotExist indicates an expected call of IsNotExist.
func (mr *MockOsIMockRecorder) IsNotExist(err any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LookupEnv mocks base method.
func (m *MockOsI) LookupEnv(key string) (string, bool) { _ = "STUB: not implemented"; return "", false }

// LookupEnv indicates an expected call of LookupEnv.
func (mr *MockOsIMockRecorder) LookupEnv(key any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MkdirAll mocks base method.
func (m *MockOsI) MkdirAll(path string, perm os.FileMode) error {
	_ = "STUB: not implemented"
	return nil
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockOsIMockRecorder) MkdirAll(path, perm any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Open mocks base method.
func (m *MockOsI) Open(name string) (*os.File, error) { _ = "STUB: not implemented"; return nil, nil }

// Open indicates an expected call of Open.
func (mr *MockOsIMockRecorder) Open(name any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// OpenFile mocks base method.
func (m *MockOsI) OpenFile(name string, flag int, perm os.FileMode) (*os.File, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockOsIMockRecorder) OpenFile(name, flag, perm any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Remove mocks base method.
func (m *MockOsI) Remove(name string) error { _ = "STUB: not implemented"; return nil }

// Remove indicates an expected call of Remove.
func (mr *MockOsIMockRecorder) Remove(name any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// Stat mocks base method.
func (m *MockOsI) Stat(name string) (os.FileInfo, error) {
	_ = "STUB: not implemented"
	return *new(os.FileInfo), nil
}

// Stat indicates an expected call of Stat.
func (mr *MockOsIMockRecorder) Stat(name any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// UserHomeDir mocks base method.
func (m *MockOsI) UserHomeDir() (string, error) { _ = "STUB: not implemented"; return "", nil }

// UserHomeDir indicates an expected call of UserHomeDir.
func (mr *MockOsIMockRecorder) UserHomeDir() *gomock.Call { _ = "STUB: not implemented"; return nil }
