// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/utils/sysUtils (interfaces: ZipI)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/utils/sysUtils/mock_archive.go -package mock_sysUtils github.com/rudderlabs/rudder-server/utils/sysUtils ZipI
//

// Package mock_sysUtils is a generated GoMock package.
package mock_sysUtils

import (
	zip "archive/zip"
	io "io"
	os "os"

	gomock "go.uber.org/mock/gomock"
)

// MockZipI is a mock of ZipI interface.
type MockZipI struct {
	ctrl     *gomock.Controller
	recorder *MockZipIMockRecorder
	isgomock struct{}
}

// MockZipIMockRecorder is the mock recorder for MockZipI.
type MockZipIMockRecorder struct {
	mock *MockZipI
}

// NewMockZipI creates a new mock instance.
func NewMockZipI(ctrl *gomock.Controller) *MockZipI { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockZipI) EXPECT() *MockZipIMockRecorder {
	_ = "STUB: not implemented"

	// FileInfoHeader mocks base method.
	return nil
}

func (m *MockZipI) FileInfoHeader(fi os.FileInfo) (*zip.FileHeader, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// FileInfoHeader indicates an expected call of FileInfoHeader.
func (mr *MockZipIMockRecorder) FileInfoHeader(fi any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NewWriter mocks base method.
func (m *MockZipI) NewWriter(w io.Writer) *zip.Writer { _ = "STUB: not implemented"; return nil }

// NewWriter indicates an expected call of NewWriter.
func (mr *MockZipIMockRecorder) NewWriter(w any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OpenReader mocks base method.
func (m *MockZipI) OpenReader(name string) (*zip.ReadCloser, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// OpenReader indicates an expected call of OpenReader.
func (mr *MockZipIMockRecorder) OpenReader(name any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
