// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/utils/sysUtils (interfaces: IoI,IoUtilI)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/utils/sysUtils/mock_io.go -package mock_sysUtils github.com/rudderlabs/rudder-server/utils/sysUtils IoI,IoUtilI
//

// Package mock_sysUtils is a generated GoMock package.
package mock_sysUtils

import (
	io "io"
	os "os"

	gomock "go.uber.org/mock/gomock"
)

// MockIoI is a mock of IoI interface.
type MockIoI struct {
	ctrl     *gomock.Controller
	recorder *MockIoIMockRecorder
	isgomock struct{}
}

// MockIoIMockRecorder is the mock recorder for MockIoI.
type MockIoIMockRecorder struct {
	mock *MockIoI
}

// NewMockIoI creates a new mock instance.
func NewMockIoI(ctrl *gomock.Controller) *MockIoI { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIoI) EXPECT() *MockIoIMockRecorder {
	_ = "STUB: not implemented"

	// Copy mocks base method.
	return nil
}

func (m *MockIoI) Copy(dst io.Writer, src io.Reader) (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// Copy indicates an expected call of Copy.
func (mr *MockIoIMockRecorder) Copy(dst, src any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockIoUtilI is a mock of IoUtilI interface.
type MockIoUtilI struct {
	ctrl     *gomock.Controller
	recorder *MockIoUtilIMockRecorder
	isgomock struct{}
}

// MockIoUtilIMockRecorder is the mock recorder for MockIoUtilI.
type MockIoUtilIMockRecorder struct {
	mock *MockIoUtilI
}

// NewMockIoUtilI creates a new mock instance.
func NewMockIoUtilI(ctrl *gomock.Controller) *MockIoUtilI { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIoUtilI) EXPECT() *MockIoUtilIMockRecorder {
	_ = "STUB: not implemented"

	// NopCloser mocks base method.
	return nil
}

func (m *MockIoUtilI) NopCloser(r io.Reader) io.ReadCloser {
	_ = "STUB: not implemented"
	return *new(io.ReadCloser)
}

// NopCloser indicates an expected call of NopCloser.
func (mr *MockIoUtilIMockRecorder) NopCloser(r any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReadAll mocks base method.
func (m *MockIoUtilI) ReadAll(r io.Reader) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockIoUtilIMockRecorder) ReadAll(r any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReadFile mocks base method.
func (m *MockIoUtilI) ReadFile(filename string) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockIoUtilIMockRecorder) ReadFile(filename any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WriteFile mocks base method.
func (m *MockIoUtilI) WriteFile(filename string, data []byte, perm os.FileMode) error {
	_ = "STUB: not implemented"
	return nil
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockIoUtilIMockRecorder) WriteFile(filename, data, perm any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
