// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/utils/sysUtils (interfaces: HTTPClientI)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/utils/sysUtils/mock_httpclient.go -package mock_sysUtils github.com/rudderlabs/rudder-server/utils/sysUtils HTTPClientI
//

// Package mock_sysUtils is a generated GoMock package.
package mock_sysUtils

import (
	http "net/http"

	gomock "go.uber.org/mock/gomock"
)

// MockHTTPClientI is a mock of HTTPClientI interface.
type MockHTTPClientI struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientIMockRecorder
	isgomock struct{}
}

// MockHTTPClientIMockRecorder is the mock recorder for MockHTTPClientI.
type MockHTTPClientIMockRecorder struct {
	mock *MockHTTPClientI
}

// NewMockHTTPClientI creates a new mock instance.
func NewMockHTTPClientI(ctrl *gomock.Controller) *MockHTTPClientI {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClientI) EXPECT() *MockHTTPClientIMockRecorder {
	_ = "STUB: not implemented"

	// Do mocks base method.
	return nil
}

func (m *MockHTTPClientI) Do(req *http.Request) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Do indicates an expected call of Do.
func (mr *MockHTTPClientIMockRecorder) Do(req any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
