// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/utils/sysUtils (interfaces: HttpI)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/utils/sysUtils/mock_http.go -package mock_sysUtils github.com/rudderlabs/rudder-server/utils/sysUtils HttpI
//

// Package mock_sysUtils is a generated GoMock package.
package mock_sysUtils

import (
	context "context"
	io "io"
	http "net/http"

	gomock "go.uber.org/mock/gomock"
)

// MockHttpI is a mock of HttpI interface.
type MockHttpI struct {
	ctrl     *gomock.Controller
	recorder *MockHttpIMockRecorder
	isgomock struct{}
}

// MockHttpIMockRecorder is the mock recorder for MockHttpI.
type MockHttpIMockRecorder struct {
	mock *MockHttpI
}

// NewMockHttpI creates a new mock instance.
func NewMockHttpI(ctrl *gomock.Controller) *MockHttpI { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpI) EXPECT() *MockHttpIMockRecorder {
	_ = "STUB: not implemented"

	// NewRequest mocks base method.
	return nil
}

func (m *MockHttpI) NewRequest(method, url string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewRequest indicates an expected call of NewRequest.
func (mr *MockHttpIMockRecorder) NewRequest(method, url, body any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NewRequestWithContext mocks base method.
func (m *MockHttpI) NewRequestWithContext(ctx context.Context, method, url string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewRequestWithContext indicates an expected call of NewRequestWithContext.
func (mr *MockHttpIMockRecorder) NewRequestWithContext(ctx, method, url, body any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
