// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/debugger/destination/ (interfaces: DestinationDebugger)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/services/debugger/destination/eventDeliveryStatusUploader.go -package mock_destinationdebugger github.com/rudderlabs/rudder-server/services/debugger/destination/ DestinationDebugger
//

// Package mock_destinationdebugger is a generated GoMock package.
package mock_destinationdebugger

import (
	destinationdebugger "github.com/rudderlabs/rudder-server/services/debugger/destination"
	gomock "go.uber.org/mock/gomock"
)

// MockDestinationDebugger is a mock of DestinationDebugger interface.
type MockDestinationDebugger struct {
	ctrl     *gomock.Controller
	recorder *MockDestinationDebuggerMockRecorder
	isgomock struct{}
}

// MockDestinationDebuggerMockRecorder is the mock recorder for MockDestinationDebugger.
type MockDestinationDebuggerMockRecorder struct {
	mock *MockDestinationDebugger
}

// NewMockDestinationDebugger creates a new mock instance.
func NewMockDestinationDebugger(ctrl *gomock.Controller) *MockDestinationDebugger {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDestinationDebugger) EXPECT() *MockDestinationDebuggerMockRecorder {
	_ = "STUB: not implemented"

	// HasUploadEnabled mocks base method.
	return nil
}

func (m *MockDestinationDebugger) HasUploadEnabled(destID string) bool {
	_ = "STUB: not implemented"
	return false
}

// HasUploadEnabled indicates an expected call of HasUploadEnabled.
func (mr *MockDestinationDebuggerMockRecorder) HasUploadEnabled(destID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecordEventDeliveryStatus mocks base method.
func (m *MockDestinationDebugger) RecordEventDeliveryStatus(destinationID string, deliveryStatus *destinationdebugger.DeliveryStatusT) bool {
	_ = "STUB: not implemented"
	return false
}

// RecordEventDeliveryStatus indicates an expected call of RecordEventDeliveryStatus.
func (mr *MockDestinationDebuggerMockRecorder) RecordEventDeliveryStatus(destinationID, deliveryStatus any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stop mocks base method.
func (m *MockDestinationDebugger) Stop() { _ = "STUB: not implemented"; return }

// Stop indicates an expected call of Stop.
func (mr *MockDestinationDebuggerMockRecorder) Stop() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
