// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/streammanager/eventbridge (interfaces: EventBridgeClient)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/services/streammanager/eventbridge/mock_eventbridge.go -package mock_eventbridge github.com/rudderlabs/rudder-server/services/streammanager/eventbridge EventBridgeClient
//

// Package mock_eventbridge is a generated GoMock package.
package mock_eventbridge

import (
	context "context"

	eventbridge "github.com/aws/aws-sdk-go-v2/service/eventbridge"
	gomock "go.uber.org/mock/gomock"
)

// MockEventBridgeClient is a mock of EventBridgeClient interface.
type MockEventBridgeClient struct {
	ctrl     *gomock.Controller
	recorder *MockEventBridgeClientMockRecorder
	isgomock struct{}
}

// MockEventBridgeClientMockRecorder is the mock recorder for MockEventBridgeClient.
type MockEventBridgeClientMockRecorder struct {
	mock *MockEventBridgeClient
}

// NewMockEventBridgeClient creates a new mock instance.
func NewMockEventBridgeClient(ctrl *gomock.Controller) *MockEventBridgeClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventBridgeClient) EXPECT() *MockEventBridgeClientMockRecorder {
	_ = "STUB: not implemented"

	// PutEvents mocks base method.
	return nil
}

func (m *MockEventBridgeClient) PutEvents(ctx context.Context, input *eventbridge.PutEventsInput, opts ...func(*eventbridge.Options)) (*eventbridge.PutEventsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutEvents indicates an expected call of PutEvents.
func (mr *MockEventBridgeClientMockRecorder) PutEvents(ctx, input any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
