// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/oauth/v2/controlplane (interfaces: HttpClient)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/services/oauth/v2/http/mock_http_client.go -package=mock_http_client github.com/rudderlabs/rudder-server/services/oauth/v2/controlplane HttpClient
//

// Package mock_http_client is a generated GoMock package.
package mock_http_client

import (
	http "net/http"

	gomock "go.uber.org/mock/gomock"
)

// MockHttpClient is a mock of HttpClient interface.
type MockHttpClient struct {
	ctrl     *gomock.Controller
	recorder *MockHttpClientMockRecorder
	isgomock struct{}
}

// MockHttpClientMockRecorder is the mock recorder for MockHttpClient.
type MockHttpClientMockRecorder struct {
	mock *MockHttpClient
}

// NewMockHttpClient creates a new mock instance.
func NewMockHttpClient(ctrl *gomock.Controller) *MockHttpClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpClient) EXPECT() *MockHttpClientMockRecorder {
	_ = "STUB: not implemented"

	// Do mocks base method.
	return nil
}

func (m *MockHttpClient) Do(req *http.Request) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Do indicates an expected call of Do.
func (mr *MockHttpClientMockRecorder) Do(req any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
