// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/salesforce-bulk-upload (interfaces: APIServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/router/salesforcebulkupload/salesforcebulkupload_mock.go -package=mocks github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/salesforce-bulk-upload APIServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	salesforcebulkupload "github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/salesforce-bulk-upload"
	gomock "go.uber.org/mock/gomock"
)

// MockAPIServiceInterface is a mock of APIServiceInterface interface.
type MockAPIServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAPIServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockAPIServiceInterfaceMockRecorder is the mock recorder for MockAPIServiceInterface.
type MockAPIServiceInterfaceMockRecorder struct {
	mock *MockAPIServiceInterface
}

// NewMockAPIServiceInterface creates a new mock instance.
func NewMockAPIServiceInterface(ctrl *gomock.Controller) *MockAPIServiceInterface {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIServiceInterface) EXPECT() *MockAPIServiceInterfaceMockRecorder {
	_ = "STUB: not implemented"

	// CloseJob mocks base method.
	return nil
}

func (m *MockAPIServiceInterface) CloseJob(jobID string) *salesforcebulkupload.APIError {
	_ = "STUB: not implemented"
	return nil
}

// CloseJob indicates an expected call of CloseJob.
func (mr *MockAPIServiceInterfaceMockRecorder) CloseJob(jobID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateJob mocks base method.
func (m *MockAPIServiceInterface) CreateJob(objectName, operation, externalIDField string) (string, *salesforcebulkupload.APIError) {
	_ = "STUB: not implemented"
	return "", nil
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockAPIServiceInterfaceMockRecorder) CreateJob(objectName, operation, externalIDField any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteJob mocks base method.
func (m *MockAPIServiceInterface) DeleteJob(jobID string) *salesforcebulkupload.APIError {
	_ = "STUB: not implemented"
	return nil
}

// DeleteJob indicates an expected call of DeleteJob.
func (mr *MockAPIServiceInterfaceMockRecorder) DeleteJob(jobID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetFailedRecords mocks base method.
func (m *MockAPIServiceInterface) GetFailedRecords(jobID string) ([]map[string]string, *salesforcebulkupload.APIError) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFailedRecords indicates an expected call of GetFailedRecords.
func (mr *MockAPIServiceInterfaceMockRecorder) GetFailedRecords(jobID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetJobStatus mocks base method.
func (m *MockAPIServiceInterface) GetJobStatus(jobID string) (*salesforcebulkupload.JobResponse, *salesforcebulkupload.APIError) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetJobStatus indicates an expected call of GetJobStatus.
func (mr *MockAPIServiceInterfaceMockRecorder) GetJobStatus(jobID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSuccessfulRecords mocks base method.
func (m *MockAPIServiceInterface) GetSuccessfulRecords(jobID string) ([]map[string]string, *salesforcebulkupload.APIError) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSuccessfulRecords indicates an expected call of GetSuccessfulRecords.
func (mr *MockAPIServiceInterfaceMockRecorder) GetSuccessfulRecords(jobID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UploadData mocks base method.
func (m *MockAPIServiceInterface) UploadData(jobID, csvFilePath string) *salesforcebulkupload.APIError {
	_ = "STUB: not implemented"
	return nil
}

// UploadData indicates an expected call of UploadData.
func (mr *MockAPIServiceInterfaceMockRecorder) UploadData(jobID, csvFilePath any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
