// Code generated by MockGen. DO NOT EDIT.
// Source: upload.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/upload.go -package=mocks -source=upload.go loadFilesRepo,stagingFilesRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	time "time"

	model "github.com/rudderlabs/rudder-server/warehouse/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockloadFilesRepo is a mock of loadFilesRepo interface.
type MockloadFilesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockloadFilesRepoMockRecorder
	isgomock struct{}
}

// MockloadFilesRepoMockRecorder is the mock recorder for MockloadFilesRepo.
type MockloadFilesRepoMockRecorder struct {
	mock *MockloadFilesRepo
}

// NewMockloadFilesRepo creates a new mock instance.
func NewMockloadFilesRepo(ctrl *gomock.Controller) *MockloadFilesRepo {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockloadFilesRepo) EXPECT() *MockloadFilesRepoMockRecorder {
	_ = "STUB: not implemented"

	// Delete mocks base method.
	return nil
}

func (m *MockloadFilesRepo) Delete(ctx context.Context, uploadID int64) error {
	_ = "STUB: not implemented"
	return nil
}

// Delete indicates an expected call of Delete.
func (mr *MockloadFilesRepoMockRecorder) Delete(ctx, uploadID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DistinctTableName mocks base method.
func (m *MockloadFilesRepo) DistinctTableName(ctx context.Context, sourceID, destinationID string, startID, endID int64) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DistinctTableName indicates an expected call of DistinctTableName.
func (mr *MockloadFilesRepoMockRecorder) DistinctTableName(ctx, sourceID, destinationID, startID, endID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Get mocks base method.
func (m *MockloadFilesRepo) Get(ctx context.Context, uploadID int64) ([]model.LoadFile, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Get indicates an expected call of Get.
func (mr *MockloadFilesRepoMockRecorder) Get(ctx, uploadID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetByID mocks base method.
func (m *MockloadFilesRepo) GetByID(ctx context.Context, id int64) (*model.LoadFile, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetByID indicates an expected call of GetByID.
func (mr *MockloadFilesRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TotalExportedEvents mocks base method.
func (m *MockloadFilesRepo) TotalExportedEvents(ctx context.Context, uploadID int64, skipTables []string) (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// TotalExportedEvents indicates an expected call of TotalExportedEvents.
func (mr *MockloadFilesRepoMockRecorder) TotalExportedEvents(ctx, uploadID, skipTables any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockstagingFilesRepo is a mock of stagingFilesRepo interface.
type MockstagingFilesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockstagingFilesRepoMockRecorder
	isgomock struct{}
}

// MockstagingFilesRepoMockRecorder is the mock recorder for MockstagingFilesRepo.
type MockstagingFilesRepoMockRecorder struct {
	mock *MockstagingFilesRepo
}

// NewMockstagingFilesRepo creates a new mock instance.
func NewMockstagingFilesRepo(ctrl *gomock.Controller) *MockstagingFilesRepo {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstagingFilesRepo) EXPECT() *MockstagingFilesRepoMockRecorder {
	_ = "STUB: not implemented"

	// GetEventTimeRangesByUploadID mocks base method.
	return nil
}

func (m *MockstagingFilesRepo) GetEventTimeRangesByUploadID(ctx context.Context, uploadID int64) ([]model.EventTimeRange, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEventTimeRangesByUploadID indicates an expected call of GetEventTimeRangesByUploadID.
func (mr *MockstagingFilesRepoMockRecorder) GetEventTimeRangesByUploadID(ctx, uploadID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TotalEventsForUploadID mocks base method.
func (m *MockstagingFilesRepo) TotalEventsForUploadID(ctx context.Context, uploadID int64) (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// TotalEventsForUploadID indicates an expected call of TotalEventsForUploadID.
func (mr *MockstagingFilesRepoMockRecorder) TotalEventsForUploadID(ctx, uploadID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockpendingTableUploadsRepo is a mock of pendingTableUploadsRepo interface.
type MockpendingTableUploadsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockpendingTableUploadsRepoMockRecorder
	isgomock struct{}
}

// MockpendingTableUploadsRepoMockRecorder is the mock recorder for MockpendingTableUploadsRepo.
type MockpendingTableUploadsRepoMockRecorder struct {
	mock *MockpendingTableUploadsRepo
}

// NewMockpendingTableUploadsRepo creates a new mock instance.
func NewMockpendingTableUploadsRepo(ctrl *gomock.Controller) *MockpendingTableUploadsRepo {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpendingTableUploadsRepo) EXPECT() *MockpendingTableUploadsRepoMockRecorder {
	_ = "STUB: not implemented"

	// PendingTableUploads mocks base method.
	return nil
}

func (m *MockpendingTableUploadsRepo) PendingTableUploads(ctx context.Context, destID, namespace string, priority int, firstEventAt time.Time, uploadID int64) ([]model.PendingTableUpload, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PendingTableUploads indicates an expected call of PendingTableUploads.
func (mr *MockpendingTableUploadsRepoMockRecorder) PendingTableUploads(ctx, destID, namespace, priority, firstEventAt, uploadID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
