// Code generated by MockGen. DO NOT EDIT.
// Source: destination.go
//
// Generated by this command:
//
//	mockgen -source=destination.go -destination=mock_destination.go -package=destination github.com/rudderlabs/rudder-server/regulation-worker/internal/Destination/destination
//

// Package destination is a generated GoMock package.
package destination

import (
	context "context"

	backendconfig "github.com/rudderlabs/rudder-server/backend-config"
	pubsub "github.com/rudderlabs/rudder-server/utils/pubsub"
	gomock "go.uber.org/mock/gomock"
)

// MockdestMiddleware is a mock of destMiddleware interface.
type MockdestMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockdestMiddlewareMockRecorder
	isgomock struct{}
}

// MockdestMiddlewareMockRecorder is the mock recorder for MockdestMiddleware.
type MockdestMiddlewareMockRecorder struct {
	mock *MockdestMiddleware
}

// NewMockdestMiddleware creates a new mock instance.
func NewMockdestMiddleware(ctrl *gomock.Controller) *MockdestMiddleware {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdestMiddleware) EXPECT() *MockdestMiddlewareMockRecorder {
	_ = "STUB: not implemented"

	// Subscribe mocks base method.
	return nil
}

func (m *MockdestMiddleware) Subscribe(ctx context.Context, topic backendconfig.Topic) pubsub.DataChannel {
	_ = "STUB: not implemented"
	return *new(pubsub.DataChannel)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockdestMiddlewareMockRecorder) Subscribe(ctx, topic any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
