// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/eloqua (interfaces: EloquaService)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/router/eloqua/mock_eloqua.go -package=mock_bulkservice github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/eloqua EloquaService
//

// Package mock_bulkservice is a generated GoMock package.
package mock_bulkservice

import (
	eloqua "github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/eloqua"
	gomock "go.uber.org/mock/gomock"
)

// MockEloquaService is a mock of EloquaService interface.
type MockEloquaService struct {
	ctrl     *gomock.Controller
	recorder *MockEloquaServiceMockRecorder
	isgomock struct{}
}

// MockEloquaServiceMockRecorder is the mock recorder for MockEloquaService.
type MockEloquaServiceMockRecorder struct {
	mock *MockEloquaService
}

// NewMockEloquaService creates a new mock instance.
func NewMockEloquaService(ctrl *gomock.Controller) *MockEloquaService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEloquaService) EXPECT() *MockEloquaServiceMockRecorder {
	_ = "STUB: not implemented"

	// CheckRejectedData mocks base method.
	return nil
}

func (m *MockEloquaService) CheckRejectedData(arg0 *eloqua.HttpRequestData) (*eloqua.RejectResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CheckRejectedData indicates an expected call of CheckRejectedData.
func (mr *MockEloquaServiceMockRecorder) CheckRejectedData(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CheckSyncStatus mocks base method.
func (m *MockEloquaService) CheckSyncStatus(arg0 *eloqua.HttpRequestData) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// CheckSyncStatus indicates an expected call of CheckSyncStatus.
func (mr *MockEloquaServiceMockRecorder) CheckSyncStatus(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateImportDefinition mocks base method.
func (m *MockEloquaService) CreateImportDefinition(arg0 *eloqua.HttpRequestData, arg1 string) (*eloqua.ImportDefinition, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateImportDefinition indicates an expected call of CreateImportDefinition.
func (mr *MockEloquaServiceMockRecorder) CreateImportDefinition(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteImportDefinition mocks base method.
func (m *MockEloquaService) DeleteImportDefinition(arg0 *eloqua.HttpRequestData) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteImportDefinition indicates an expected call of DeleteImportDefinition.
func (mr *MockEloquaServiceMockRecorder) DeleteImportDefinition(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// FetchFields mocks base method.
func (m *MockEloquaService) FetchFields(arg0 *eloqua.HttpRequestData) (*eloqua.Fields, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// FetchFields indicates an expected call of FetchFields.
func (mr *MockEloquaServiceMockRecorder) FetchFields(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBaseEndpoint mocks base method.
func (m *MockEloquaService) GetBaseEndpoint(arg0 *eloqua.HttpRequestData) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetBaseEndpoint indicates an expected call of GetBaseEndpoint.
func (mr *MockEloquaServiceMockRecorder) GetBaseEndpoint(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RunSync mocks base method.
func (m *MockEloquaService) RunSync(arg0 *eloqua.HttpRequestData) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// RunSync indicates an expected call of RunSync.
func (mr *MockEloquaServiceMockRecorder) RunSync(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UploadData mocks base method.
func (m *MockEloquaService) UploadData(arg0 *eloqua.HttpRequestData, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// UploadData indicates an expected call of UploadData.
func (mr *MockEloquaServiceMockRecorder) UploadData(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
