// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/dedup/types (interfaces: Dedup)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/services/dedup/mock_dedup.go -package mock_dedup github.com/rudderlabs/rudder-server/services/dedup/types Dedup
//

// Package mock_dedup is a generated GoMock package.
package mock_dedup

import (
	types "github.com/rudderlabs/rudder-server/services/dedup/types"
	gomock "go.uber.org/mock/gomock"
)

// MockDedup is a mock of Dedup interface.
type MockDedup struct {
	ctrl     *gomock.Controller
	recorder *MockDedupMockRecorder
	isgomock struct{}
}

// MockDedupMockRecorder is the mock recorder for MockDedup.
type MockDedupMockRecorder struct {
	mock *MockDedup
}

// NewMockDedup creates a new mock instance.
func NewMockDedup(ctrl *gomock.Controller) *MockDedup { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDedup) EXPECT() *MockDedupMockRecorder {
	_ = "STUB: not implemented"

	// Allowed mocks base method.
	return nil
}

func (m *MockDedup) Allowed(keys ...types.BatchKey) (map[types.BatchKey]bool, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Allowed indicates an expected call of Allowed.
func (mr *MockDedupMockRecorder) Allowed(keys ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Close mocks base method.
func (m *MockDedup) Close() { _ = "STUB: not implemented"; return }

// Close indicates an expected call of Close.
func (mr *MockDedupMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Commit mocks base method.
func (m *MockDedup) Commit(keys []string) error { _ = "STUB: not implemented"; return nil }

// Commit indicates an expected call of Commit.
func (mr *MockDedupMockRecorder) Commit(keys any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
