// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/enterprise/reporting/event_sampler (interfaces: EventSampler)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/enterprise/reporting/event_sampler/mock_event_sampler.go -package=mocks github.com/rudderlabs/rudder-server/enterprise/reporting/event_sampler EventSampler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "go.uber.org/mock/gomock"
)

// MockEventSampler is a mock of EventSampler interface.
type MockEventSampler struct {
	ctrl     *gomock.Controller
	recorder *MockEventSamplerMockRecorder
	isgomock struct{}
}

// MockEventSamplerMockRecorder is the mock recorder for MockEventSampler.
type MockEventSamplerMockRecorder struct {
	mock *MockEventSampler
}

// NewMockEventSampler creates a new mock instance.
func NewMockEventSampler(ctrl *gomock.Controller) *MockEventSampler {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventSampler) EXPECT() *MockEventSamplerMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockEventSampler) Close() { _ = "STUB: not implemented"; return }

// Close indicates an expected call of Close.
func (mr *MockEventSamplerMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Get mocks base method.
func (m *MockEventSampler) Get(key string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// Get indicates an expected call of Get.
func (mr *MockEventSamplerMockRecorder) Get(key any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Put mocks base method.
func (m *MockEventSampler) Put(key string) error { _ = "STUB: not implemented"; return nil }

// Put indicates an expected call of Put.
func (mr *MockEventSamplerMockRecorder) Put(key any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
