// Code generated by MockGen. DO NOT EDIT.
// Source: ./cache.go
//
// Generated by this command:
//
//	mockgen -destination=./mock_cache.go -package=cache -source=./cache.go cache
//

// Package cache is a generated GoMock package.
package cache

import (
	context "context"

	gomock "go.uber.org/mock/gomock"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	_ = "STUB: not implemented"

	// Get mocks base method.
	return nil
}

func (m *MockCache) Get(ctx context.Context) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Get indicates an expected call of Get.
func (mr *MockCacheMockRecorder) Get(ctx any) *gomock.Call { _ = "STUB: not implemented"; return nil }
