// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/streammanager/common (interfaces: StreamProducer)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=../../../mocks/services/streammanager/common/mock_streammanager.go -package mock_streammanager github.com/rudderlabs/rudder-server/services/streammanager/common StreamProducer
//

// Package mock_streammanager is a generated GoMock package.
package mock_streammanager

import (
	json "encoding/json"

	gomock "go.uber.org/mock/gomock"
)

// MockStreamProducer is a mock of StreamProducer interface.
type MockStreamProducer struct {
	ctrl     *gomock.Controller
	recorder *MockStreamProducerMockRecorder
	isgomock struct{}
}

// MockStreamProducerMockRecorder is the mock recorder for MockStreamProducer.
type MockStreamProducerMockRecorder struct {
	mock *MockStreamProducer
}

// NewMockStreamProducer creates a new mock instance.
func NewMockStreamProducer(ctrl *gomock.Controller) *MockStreamProducer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamProducer) EXPECT() *MockStreamProducerMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockStreamProducer) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockStreamProducerMockRecorder) Close() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Produce mocks base method.
func (m *MockStreamProducer) Produce(jsonData json.RawMessage, destConfig any) (int, string, string) {
	_ = "STUB: not implemented"
	return 0, "", ""
}

// Produce indicates an expected call of Produce.
func (mr *MockStreamProducerMockRecorder) Produce(jsonData, destConfig any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
