// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/router/transformer (interfaces: Transformer)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/router/transformer/mock_transformer.go -package=mocks_transformer github.com/rudderlabs/rudder-server/router/transformer Transformer
//

// Package mocks_transformer is a generated GoMock package.
package mocks_transformer

import (
	context "context"

	transformer "github.com/rudderlabs/rudder-server/router/transformer"
	types "github.com/rudderlabs/rudder-server/router/types"
	gomock "go.uber.org/mock/gomock"
)

// MockTransformer is a mock of Transformer interface.
type MockTransformer struct {
	ctrl     *gomock.Controller
	recorder *MockTransformerMockRecorder
	isgomock struct{}
}

// MockTransformerMockRecorder is the mock recorder for MockTransformer.
type MockTransformerMockRecorder struct {
	mock *MockTransformer
}

// NewMockTransformer creates a new mock instance.
func NewMockTransformer(ctrl *gomock.Controller) *MockTransformer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransformer) EXPECT() *MockTransformerMockRecorder {
	_ = "STUB: not implemented"

	// ProxyRequest mocks base method.
	return nil
}

func (m *MockTransformer) ProxyRequest(ctx context.Context, proxyReqParams *transformer.ProxyRequestParams) transformer.ProxyRequestResponse {
	_ = "STUB: not implemented"
	return *new(transformer.ProxyRequestResponse)
}

// ProxyRequest indicates an expected call of ProxyRequest.
func (mr *MockTransformerMockRecorder) ProxyRequest(ctx, proxyReqParams any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Transform mocks base method.
func (m *MockTransformer) Transform(transformType string, transformMessage *types.TransformMessageT) []types.DestinationJobT {
	_ = "STUB: not implemented"
	return nil
}

// Transform indicates an expected call of Transform.
func (mr *MockTransformerMockRecorder) Transform(transformType, transformMessage any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
