// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/gateway/throttler (interfaces: Throttler)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/gateway/throttler.go -package=mocks_gateway github.com/rudderlabs/rudder-server/gateway/throttler Throttler
//

// Package mocks_gateway is a generated GoMock package.
package mocks_gateway

import (
	context "context"

	gomock "go.uber.org/mock/gomock"
)

// MockThrottler is a mock of Throttler interface.
type MockThrottler struct {
	ctrl     *gomock.Controller
	recorder *MockThrottlerMockRecorder
	isgomock struct{}
}

// MockThrottlerMockRecorder is the mock recorder for MockThrottler.
type MockThrottlerMockRecorder struct {
	mock *MockThrottler
}

// NewMockThrottler creates a new mock instance.
func NewMockThrottler(ctrl *gomock.Controller) *MockThrottler {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThrottler) EXPECT() *MockThrottlerMockRecorder {
	_ = "STUB: not implemented"

	// CheckLimitReached mocks base method.
	return nil
}

func (m *MockThrottler) CheckLimitReached(arg0 context.Context, workspaceId string, eventCount int64) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// CheckLimitReached indicates an expected call of CheckLimitReached.
func (mr *MockThrottlerMockRecorder) CheckLimitReached(arg0, workspaceId, eventCount any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
