// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/gateway/webhook (interfaces: WebhookRequestHandler)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/gateway/webhook.go -package=mocks_gateway github.com/rudderlabs/rudder-server/gateway/webhook WebhookRequestHandler
//

// Package mocks_gateway is a generated GoMock package.
package mocks_gateway

import (
	http "net/http"

	gomock "go.uber.org/mock/gomock"
)

// MockWebhookRequestHandler is a mock of WebhookRequestHandler interface.
type MockWebhookRequestHandler struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookRequestHandlerMockRecorder
	isgomock struct{}
}

// MockWebhookRequestHandlerMockRecorder is the mock recorder for MockWebhookRequestHandler.
type MockWebhookRequestHandlerMockRecorder struct {
	mock *MockWebhookRequestHandler
}

// NewMockWebhookRequestHandler creates a new mock instance.
func NewMockWebhookRequestHandler(ctrl *gomock.Controller) *MockWebhookRequestHandler {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookRequestHandler) EXPECT() *MockWebhookRequestHandlerMockRecorder {
	_ = "STUB: not implemented"

	// Register mocks base method.
	return nil
}

func (m *MockWebhookRequestHandler) Register(name string) { _ = "STUB: not implemented"; return }

// Register indicates an expected call of Register.
func (mr *MockWebhookRequestHandlerMockRecorder) Register(name any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RequestHandler mocks base method.
func (m *MockWebhookRequestHandler) RequestHandler(w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// RequestHandler indicates an expected call of RequestHandler.
func (mr *MockWebhookRequestHandlerMockRecorder) RequestHandler(w, r any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Shutdown mocks base method.
func (m *MockWebhookRequestHandler) Shutdown() error { _ = "STUB: not implemented"; return nil }

// Shutdown indicates an expected call of Shutdown.
func (mr *MockWebhookRequestHandlerMockRecorder) Shutdown() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
