// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/debugger/source (interfaces: SourceDebugger)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock.go -package=mocks github.com/rudderlabs/rudder-server/services/debugger/source SourceDebugger
//

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "go.uber.org/mock/gomock"
)

// MockSourceDebugger is a mock of SourceDebugger interface.
type MockSourceDebugger struct {
	ctrl     *gomock.Controller
	recorder *MockSourceDebuggerMockRecorder
	isgomock struct{}
}

// MockSourceDebuggerMockRecorder is the mock recorder for MockSourceDebugger.
type MockSourceDebuggerMockRecorder struct {
	mock *MockSourceDebugger
}

// NewMockSourceDebugger creates a new mock instance.
func NewMockSourceDebugger(ctrl *gomock.Controller) *MockSourceDebugger {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceDebugger) EXPECT() *MockSourceDebuggerMockRecorder {
	_ = "STUB: not implemented"

	// RecordEvent mocks base method.
	return nil
}

func (m *MockSourceDebugger) RecordEvent(writeKey string, eventBatch []byte) bool {
	_ = "STUB: not implemented"
	return false
}

// RecordEvent indicates an expected call of RecordEvent.
func (mr *MockSourceDebuggerMockRecorder) RecordEvent(writeKey, eventBatch any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stop mocks base method.
func (m *MockSourceDebugger) Stop() { _ = "STUB: not implemented"; return }

// Stop indicates an expected call of Stop.
func (mr *MockSourceDebuggerMockRecorder) Stop() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
