// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/streammanager/googlecloudfunction (interfaces: GoogleCloudFunctionClient)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/services/streammanager/googlecloudfunction/mock_googlecloudfunction.go -package mock_googlecloudfunction github.com/rudderlabs/rudder-server/services/streammanager/googlecloudfunction GoogleCloudFunctionClient
//

// Package mock_googlecloudfunction is a generated GoMock package.
package mock_googlecloudfunction

import (
	context "context"

	gomock "go.uber.org/mock/gomock"
	oauth2 "golang.org/x/oauth2"
	option "google.golang.org/api/option"
)

// MockGoogleCloudFunctionClient is a mock of GoogleCloudFunctionClient interface.
type MockGoogleCloudFunctionClient struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleCloudFunctionClientMockRecorder
	isgomock struct{}
}

// MockGoogleCloudFunctionClientMockRecorder is the mock recorder for MockGoogleCloudFunctionClient.
type MockGoogleCloudFunctionClientMockRecorder struct {
	mock *MockGoogleCloudFunctionClient
}

// NewMockGoogleCloudFunctionClient creates a new mock instance.
func NewMockGoogleCloudFunctionClient(ctrl *gomock.Controller) *MockGoogleCloudFunctionClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleCloudFunctionClient) EXPECT() *MockGoogleCloudFunctionClientMockRecorder {
	_ = "STUB: not implemented"

	// GetToken mocks base method.
	return nil
}

func (m *MockGoogleCloudFunctionClient) GetToken(ctx context.Context, functionUrl string, opts ...option.ClientOption) (*oauth2.Token, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetToken indicates an expected call of GetToken.
func (mr *MockGoogleCloudFunctionClientMockRecorder) GetToken(ctx, functionUrl any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
