// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/utils/types (interfaces: UserSuppression,Reporting)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/utils/types/mock_types.go -package mock_types github.com/rudderlabs/rudder-server/utils/types UserSuppression,Reporting
//

// Package mock_types is a generated GoMock package.
package mock_types

import (
	context "context"

	model "github.com/rudderlabs/rudder-server/enterprise/suppress-user/model"
	tx "github.com/rudderlabs/rudder-server/utils/tx"
	types "github.com/rudderlabs/rudder-server/utils/types"
	gomock "go.uber.org/mock/gomock"
)

// MockUserSuppression is a mock of UserSuppression interface.
type MockUserSuppression struct {
	ctrl     *gomock.Controller
	recorder *MockUserSuppressionMockRecorder
	isgomock struct{}
}

// MockUserSuppressionMockRecorder is the mock recorder for MockUserSuppression.
type MockUserSuppressionMockRecorder struct {
	mock *MockUserSuppression
}

// NewMockUserSuppression creates a new mock instance.
func NewMockUserSuppression(ctrl *gomock.Controller) *MockUserSuppression {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSuppression) EXPECT() *MockUserSuppressionMockRecorder {
	_ = "STUB: not implemented"

	// GetSuppressedUser mocks base method.
	return nil
}

func (m *MockUserSuppression) GetSuppressedUser(workspaceID, userID, sourceID string) *model.Metadata {
	_ = "STUB: not implemented"
	return nil
}

// GetSuppressedUser indicates an expected call of GetSuppressedUser.
func (mr *MockUserSuppressionMockRecorder) GetSuppressedUser(workspaceID, userID, sourceID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockReporting is a mock of Reporting interface.
type MockReporting struct {
	ctrl     *gomock.Controller
	recorder *MockReportingMockRecorder
	isgomock struct{}
}

// MockReportingMockRecorder is the mock recorder for MockReporting.
type MockReportingMockRecorder struct {
	mock *MockReporting
}

// NewMockReporting creates a new mock instance.
func NewMockReporting(ctrl *gomock.Controller) *MockReporting {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporting) EXPECT() *MockReportingMockRecorder {
	_ = "STUB: not implemented"

	// DatabaseSyncer mocks base method.
	return nil
}

func (m *MockReporting) DatabaseSyncer(c types.SyncerConfig) types.ReportingSyncer {
	_ = "STUB: not implemented"
	return *new(types.ReportingSyncer)
}

// DatabaseSyncer indicates an expected call of DatabaseSyncer.
func (mr *MockReportingMockRecorder) DatabaseSyncer(c any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Report mocks base method.
func (m *MockReporting) Report(ctx context.Context, metrics []*types.PUReportedMetric, arg2 *tx.Tx) error {
	_ = "STUB: not implemented"
	return nil
}

// Report indicates an expected call of Report.
func (mr *MockReportingMockRecorder) Report(ctx, metrics, arg2 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stop mocks base method.
func (m *MockReporting) Stop() { _ = "STUB: not implemented"; return }

// Stop indicates an expected call of Stop.
func (mr *MockReportingMockRecorder) Stop() *gomock.Call { _ = "STUB: not implemented"; return nil }
